<?php
function att_save_event(PDO $db,array $actor,array $in):int {
 if(!can($db,$actor,'calendar.manage'))throw new InvalidArgumentException('Calendar editing is not permitted.');$v=['type'=>ftext($in,'type',50,true),'start'=>chr_date((string)($in['start']??'')),'end'=>chr_date((string)($in['end']??'')),'all_day'=>!empty($in['all_day']),'description'=>ftext($in,'description',5000),'location'=>ftext($in,'location',250),'audience'=>$in['audience']??''];
 if(!in_array($v['type'],['Meeting','Training','Celebration','Company Event'],true))throw new InvalidArgumentException('Select an event type.');if($v['end']<$v['start'])throw new InvalidArgumentException('End date cannot precede start date.');if(!in_array($v['audience'],['Everyone','Department','Selected Employees'],true))throw new InvalidArgumentException('Select an audience.');
 $v['start_time']=$v['all_day']?null:chr_time($in,'start_time');$v['end_time']=$v['all_day']?null:chr_time($in,'end_time');if(!$v['all_day']&&$v['end']===$v['start']&&$v['end_time']<=$v['start_time'])throw new InvalidArgumentException('End time must follow start time.');$v['department_id']=null;$v['employee_ids']=[];
 if($v['audience']==='Department'){$id=(int)($in['department_id']??0);$q=$db->prepare('SELECT id FROM departments WHERE id=? AND active=1');$q->execute([$id]);if(!$q->fetchColumn())throw new InvalidArgumentException('Choose an active department.');$v['department_id']=$id;}
 if($v['audience']==='Selected Employees'){$v['employee_ids']=array_values(array_unique(array_map('intval',(array)($in['employee_ids']??[]))));if(!$v['employee_ids'])throw new InvalidArgumentException('Select at least one employee.');foreach($v['employee_ids'] as $id)att_active_employee($db,$id);}
 $db->beginTransaction();try{chr_lock($db);$id=att_record_write($db,$actor,'company_events',$in,$v,null,!empty($in['active'])?'Active':'Cancelled');$db->commit();return $id;}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
}
