<?php
require_once __DIR__.'/insights.php';$insights=att_insights($rows);
$pending=(int)$pdo->query("SELECT COUNT(*) FROM hr_requests WHERE kind='regularisation' AND status='Pending'")->fetchColumn();
?>
<div class="att-section-heading"><div><p class="eyebrow">DAILY PULSE</p><h2><?=h(date('l, d F Y',strtotime($from)))?></h2><p>Attendance across your selected employees, departments and shifts.</p></div><?php if(can($pdo,$user,'attendance.view')):?><a class="button" href="?page=attendance_requests">Review requests · <?=$pending?></a><?php endif;?></div>
<form class="card att-filter" method="get"><?php chr_hidden('page',$page);field('date','Date',['date'=>$day],'date',true);chr_select('department_id','Department',$_GET['department_id']??'', [''=>'All departments']+$departmentOptions);chr_select('employee_id','Employee',$_GET['employee_id']??'', [''=>'All employees']+$historyEmployeeOptions);chr_select('shift_id','Shift',$_GET['shift_id']??'', [''=>'All shifts']+$shiftOptions);?><button class="button primary">Apply filters</button></form>
<div class="att-kpis"><?php foreach(['arrivals'=>['Checked in','Employees with a recorded check-in'],'on_time'=>['On time','Recorded check-ins with no lateness'],'late'=>['Late arrivals','Against the assigned shift and grace'],'absent'=>['Absent days','Recorded or completed scheduled absence']] as $key=>[$label,$hint]):?><section class="card att-kpi"><p><?=h($label)?></p><strong><?=h($insights[$key])?></strong><small><?=h($hint)?></small></section><?php endforeach;?></div>
<div class="att-insight-grid">
<section class="card"><div class="att-panel-heading"><h2>Team snapshot</h2><span class="att-tag"><?=count($insights['departments'])?> departments</span></div><p class="att-caption">Checked-in employees and absent day equivalents. Pending days are not marked absent.</p><div class="att-legend"><span><i class="att-present"></i>Checked in</span><span><i class="att-absent"></i>Absent</span></div>
<?php $teams=array_values($insights['departments']);usort($teams,fn($a,$b)=>$b['arrivals']<=>$a['arrivals']);$max=max(1,...array_map(fn($d)=>$d['arrivals']+$d['absent'],$teams));if(!$teams):?><p class="att-empty">No matching employees.</p><?php endif;?><ol class="att-bars att-chart-scroll"><?php foreach($teams as $d):?><li><div class="att-bar-label"><span><?=h($d['label'])?></span><strong><?=$d['arrivals']?> / <?=$d['absent']?></strong></div><div class="att-stack" aria-hidden="true"><span class="att-present" style="width:<?=$d['arrivals']/$max*100?>%"></span><span class="att-absent" style="width:<?=$d['absent']/$max*100?>%"></span></div></li><?php endforeach;?></ol></section>
<section class="card"><div class="att-panel-heading"><h2>Late arrivals to review</h2><span class="att-tag">Selected date</span></div><p class="att-caption">Employees ranked by minutes late for this date.</p><?php $late=array_values(array_filter($insights['employees'],fn($e)=>$e['late']>0));usort($late,fn($a,$b)=>$b['late_minutes']<=>$a['late_minutes']);att_insight_bars(array_slice($late,0,5),'late_minutes',' min');?><a class="att-text-link" href="?<?=h(http_build_query(['page'=>'attendance_exceptions','date'=>$from]+array_intersect_key($_GET,array_flip(['employee_id','department_id','shift_id']))))?>">View late arrivals and early departures →</a></section>
</div>
<section class="card att-summary-strip"><div><small>Recorded working time</small><strong><?=h(chr_hours($insights['worked']))?></strong></div><div><small>Recorded overtime</small><strong><?=h(chr_hours($insights['overtime']))?></strong></div><p>Open shifts may not yet have final hours. Correction requests are reviewed separately.</p><a class="button" href="?page=daily_work_status&month=<?=h(substr($from,0,7))?>">Open Attendance Sheet</a></section>
