<?php att_require_biometric($pdo); ?>
<nav class="tabs" aria-label="Biometric devices sections"><?php foreach(['devices'=>'Devices','mapping'=>'Employee Mapping','punch_log'=>'Check-In / Check-Out Log','sync'=>'Sync Logs','raw_logs'=>'Raw Punch Logs'] as $biometricPage=>$biometricLabel):if(!can($pdo,$user,$pages[$biometricPage][1]))continue;?><a href="?page=<?=h($biometricPage)?>" <?=($page===$biometricPage)?'class="active" aria-current="page"':''?>><?=h($biometricLabel)?></a><?php endforeach;?></nav>
<?php $devices=chr_rows($pdo,'devices');$deviceOptions=[];foreach($devices as $device)$deviceOptions[$device['id']]=$device['title'].' · '.$device['values']['device_code'];
if(isset($_SESSION['bridge_token_once'])):$once=$_SESSION['bridge_token_once'];unset($_SESSION['bridge_token_once']);?><section class="card"><h2>New token · <?=h($once['serial'])?></h2><p>Copy this token into the office bridge configuration. It is displayed once.</p><code style="overflow-wrap:anywhere"><?=h($once['token'])?></code></section><?php endif;
if(in_array($page,['devices','mapping'],true)&&can($pdo,$user,'biometric.manage')):$edit=isset($_GET['edit'])?chr_record($pdo,$page,(int)$_GET['edit']):null;$v=$edit?array_merge($edit,$edit['values']):[];
?><details class="card" <?=$edit?'open':''?>><summary><?=$edit?'Edit':'Add'?> <?=$page==='devices'?'device':'employee mapping'?></summary><form method="post" class="form-grid"><?php ftoken();chr_hidden('action',$page==='devices'?'att_device':'att_mapping');chr_hidden('id',$edit['id']??0);chr_hidden('version',$edit['version']??0);field('title','Name',$v,'text',true,190);if($page==='devices'){field('device_code','Device serial',$v,'text',true,80);field('model','Device model',$v);field('host','Office LAN IP / host',$v);field('location','Location',$v);field('notes','Notes',$v,'text',false,2000);}else{$selected='';foreach($devices as $d)if(($v['device_code']??'')===$d['values']['device_code'])$selected=$d['id'];chr_select('device_id','Device',$selected,[''=>'Select device']+$deviceOptions);chr_select('employee_id','Employee',$v['employee_id']??'',[''=>'Select employee']+$employeeOptions);field('biometric_id','Device user ID',$v,'text',true,80);}chr_checkbox('active','Active',!$edit||in_array($edit['status'],['Active','Enabled'],true));?><button class="button primary">Save</button></form></details><?php endif;
if($page==='devices'):foreach($devices as $device):$q=$pdo->prepare('SELECT *,TIMESTAMPDIFF(SECOND,last_seen,NOW()) heartbeat_age,UNIX_TIMESTAMP(last_seen) last_seen_epoch,UNIX_TIMESTAMP(last_success) last_success_epoch FROM hr_bridge_health WHERE device_id=?');$q->execute([$device['id']]);$health=$q->fetch(PDO::FETCH_ASSOC)?:[];$recent=isset($health['heartbeat_age'])&&(int)$health['heartbeat_age']>=0&&(int)$health['heartbeat_age']<300;?>
<section class="card biometric-card">
<header class="biometric-card-heading"><div><p class="biometric-kicker">ATTENDANCE DEVICE</p><h2><?=h($device['title'])?></h2><p class="biometric-meta"><?=h($device['values']['model']??'eSSL')?> · <?=h($device['values']['device_code'])?><?php if(!empty($device['values']['location'])):?> · <?=h($device['values']['location'])?><?php endif;?></p></div><?php fbadge($device['status'],$device['status']==='Enabled');?></header>
<div class="biometric-health">
<div><span class="biometric-label">Bridge connection</span><strong class="biometric-state <?=$recent?'is-connected':'is-pending'?>"><?=$recent?'Recently connected':'Heartbeat overdue'?></strong><small><?=$recent?'Heartbeat received in the last 5 minutes':'No heartbeat in the last 5 minutes'?></small></div>
<div><span class="biometric-label">Device connection</span><strong class="biometric-state <?=$recent&&!empty($health['device_online'])?'is-connected':'is-pending'?>"><?=$recent&&!empty($health['device_online'])?'Reachable at last test':'Not confirmed'?></strong><small><?=$recent&&!empty($health['device_online'])?'Based on the bridge’s last device test':'Check the office bridge log'?></small></div>
</div>
<dl class="biometric-times"><div><dt>Last heartbeat</dt><dd><?=h(!empty($health['last_seen_epoch'])?date('d M Y · H:i:s T',(int)$health['last_seen_epoch']):'Not received yet')?></dd></div><div><dt>Last saved batch</dt><dd><?=h(!empty($health['last_success_epoch'])?date('d M Y · H:i:s T',(int)$health['last_success_epoch']):'No batch saved yet')?></dd></div></dl>
<?php if(!empty($health['last_error'])):?><div class="alert error"><?=h($health['last_error'])?></div><?php endif;?>
<footer class="biometric-actions"><div class="biometric-primary-actions">
<?php if(can($pdo,$user,'biometric.sync')):?><form method="post"><?php ftoken();chr_hidden('action','att_device_action');chr_hidden('device_id',$device['id']);?><button class="button primary" name="device_action" value="sync">Request sync</button><button class="button" name="device_action" value="test">Test connection</button></form><?php endif;?>
<?php if(can($pdo,$user,'biometric.manage')):?><a class="button" href="?page=devices&edit=<?=$device['id']?>">Edit device</a><?php endif;?></div>
<?php if(can($pdo,$user,'biometric.manage')):?><details class="biometric-token-actions"><summary>Token settings</summary><p class="hint">Manage the access token used by your office bridge.</p><form method="post"><?php ftoken();chr_hidden('action','att_device_action');chr_hidden('device_id',$device['id']);?><button class="button" name="device_action" value="rotate">Generate / rotate token</button><button class="button danger" name="device_action" value="revoke">Revoke tokens</button></form></details><?php endif;?></footer>
</section><?php endforeach;if(!$devices):echo '<section class="card">No biometric devices registered.</section>';endif; 
elseif($page==='mapping'):
$latestPunches=[];foreach($pdo->query('SELECT device_code,biometric_id,MAX(punched_at) latest_punch FROM hr_punches GROUP BY device_code,biometric_id') as $punch)$latestPunches[$punch['device_code']][$punch['biometric_id']]=$punch['latest_punch'];
?><section class="card"><p class="hint">Latest punch received for each device and biometric ID. Times use <?=h(date_default_timezone_get())?>; this is the recorded punch time, not the mapping creation time.</p><div class="table-scroll attendance-table-scroll" tabindex="0" role="region" aria-label="Employee mappings"><table class="directory"><thead><tr><th>Device</th><th>Biometric ID</th><th>Employee</th><th>Latest Punch Date &amp; Time</th><th>Status</th><th>Action</th></tr></thead><tbody><?php foreach(chr_rows($pdo,'mapping') as $r):?><tr><td><?=h($r['values']['device_code']??'')?></td><td><?=h($r['values']['biometric_id']??'')?></td><td><?=h($historyEmployeeOptions[$r['employee_id']]??'Unavailable')?></td><td><?php $latest=$latestPunches[$r['values']['device_code']??''][$r['values']['biometric_id']??'']??null;echo h($latest?(new DateTimeImmutable($latest))->format('d M Y · H:i:s T'):'No punches received');?></td><td><?=h($r['status'])?></td><td><?php if(can($pdo,$user,'biometric.manage')):?><a href="?page=mapping&edit=<?=$r['id']?>">Edit</a><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section><?php
elseif($page==='punch_log'):require __DIR__.'/punches-view.php';
else:$columns=$page==='sync'?['device_id','started_at','received','imported','duplicates','failed','status','error_message']:['device_code','biometric_id','punched_at','direction','status','error_message'];$sql=$page==='sync'?'SELECT * FROM hr_bridge_sync ORDER BY id DESC LIMIT 500':"SELECT p.*,COALESCE(x.status,'Legacy raw') status,COALESCE(x.error_message,'') error_message FROM hr_punches p LEFT JOIN hr_punch_processing x ON x.punch_id=p.id ORDER BY p.id DESC LIMIT 500";?><section class="card"><p>Latest 500 records. Raw punches remain stored independently of calculated attendance. Pending punches retry automatically while the office bridge is running; missing mappings still need to be corrected.</p><div class="table-scroll attendance-table-scroll" tabindex="0" role="region" aria-label="Biometric records"><table class="directory"><thead><tr><?php foreach($columns as $c):?><th><?=h(ucwords(str_replace('_',' ',$c)))?></th><?php endforeach;?></tr></thead><tbody><?php foreach($pdo->query($sql) as $r):?><tr><?php foreach($columns as $c):?><td><?=h($r[$c]??'')?></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div></section><?php endif;?>
