<?php require_once __DIR__.'/insights.php';$insights=att_insights($daily);?>
<div class="att-insight-grid">
<section class="card att-wide"><div class="att-panel-heading"><div><h2>Attendance through the month</h2><p class="att-caption">Day equivalents from completed attendance and approved leave. Open and pending days are excluded.</p></div><span class="att-tag"><?=h(date('F Y',strtotime($from)))?></span></div><div class="att-legend"><span><i class="att-present"></i>Present</span><span><i class="att-absent"></i>Absent</span><span><i class="att-leave"></i>Leave</span></div>
<?php $max=max(array_merge([1],array_values(array_map(fn($d)=>array_sum($d),$insights['days']))));if(!$insights['days']):?><p class="att-empty">No matching attendance for this month.</p><?php else:?><div class="att-trend-scroll" tabindex="0" role="region" aria-label="Daily attendance chart"><div class="att-trend"><?php foreach($insights['days'] as $date=>$counts):$description=date('d M',strtotime($date)).': '.$counts['present'].' present, '.$counts['absent'].' absent, '.$counts['leave'].' leave';?><div class="att-day" tabindex="0" aria-label="<?=h($description)?>" title="<?=h($description)?>"><div class="att-day-bars" aria-hidden="true"><?php foreach(['present','absent','leave'] as $key):?><span class="att-<?=h($key)?>" style="height:<?=$counts[$key]/$max*160?>px"></span><?php endforeach;?></div><small><?=h(substr($date,8))?></small></div><?php endforeach;?></div></div><?php endif;?></section>
<section class="card"><h2>Department attendance ranking</h2><p class="att-caption">Present ÷ (present + absent) day equivalents. Leave, holidays and unresolved days do not lower this rate.</p><?php $rank=array_values(array_filter($insights['departments'],fn($d)=>$d['rate']!==null));usort($rank,fn($a,$b)=>$b['rate']<=>$a['rate']);?><div class="att-chart-scroll"><?php att_insight_bars($rank,'rate','%',100);?></div></section>
<section class="card"><h2>Most frequent late arrivals</h2><p class="att-caption">Top employees by late days; total late time breaks ties.</p><?php $late=array_values(array_filter($insights['employees'],fn($e)=>$e['late']>0));usort($late,fn($a,$b)=>($b['late']<=>$a['late'])?:($b['late_minutes']<=>$a['late_minutes']));att_insight_bars(array_slice($late,0,5),'late',' days');?></section>
<section class="card"><h2>Lateness by department</h2><p class="att-caption">Late arrivals as a percentage of recorded check-ins.</p><?php $lateTeams=array_values(array_filter($insights['departments'],fn($d)=>$d['late_rate']!==null));usort($lateTeams,fn($a,$b)=>$b['late_rate']<=>$a['late_rate']);?><div class="att-chart-scroll"><?php att_insight_bars($lateTeams,'late_rate','%',100);?></div></section>
<section class="card"><h2>Time recorded</h2><div class="att-time-summary"><div><small>Total worked</small><strong><?=h(chr_hours($insights['worked']))?></strong></div><div><small>Overtime</small><strong><?=h(chr_hours($insights['overtime']))?></strong></div></div><p class="att-caption">Uses existing attendance calculations and shift overtime rules. Open shifts may not yet have final hours.</p><a class="button" href="?page=daily_work_status&month=<?=h(substr($from,0,7))?>">View monthly sheet</a></section>
</div><div class="att-section-heading"><div><h2>Employee details</h2><p>Select a figure to see the daily records behind it.</p></div></div>
