<?php
$grid=$page==='daily_work_status';$month=$_GET['month']??date('Y-m');$day=$_GET['date']??date('Y-m-d');
?><form class="card form-grid" method="get"><?php chr_hidden('page',$page);if($grid)field('month','Month',['month'=>$month],'month',true);else field('date','Date',['date'=>$day],'date',true);chr_select('department_id','Department',$_GET['department_id']??'', [''=>'All departments']+$departmentOptions);chr_select('employee_id','Employee',$_GET['employee_id']??'', [''=>'All employees']+$historyEmployeeOptions);chr_select('shift_id','Shift',$_GET['shift_id']??'', [''=>'All shifts']+$shiftOptions);if($page==='punch_log')chr_select('source','Source',$_GET['source']??'',array_combine(['','Admin Manual','CSV Import','Biometric','Admin','Manual','Web','API','eSSL'],['All sources','Admin Manual','CSV Import','Biometric','Admin','Manual','Web','API','eSSL']));?><div><button class="button primary">Apply filters</button></div></form>
<?php try{[$from,$to]=chr_report_range($grid?'monthly':'attendance',$_GET);$rows=chr_report($pdo,$from,$to,$_GET);}catch(InvalidArgumentException $e){echo '<div class="alert error">'.h($e->getMessage()).'</div>';return;}
if($page==='attendance_dashboard'):
$cards=['Present'=>0,'On time'=>0,'Late arrivals'=>0,'Absent'=>0,'Pending requests'=>0,'Overtime minutes'=>0];$departments=[];$hours=array_fill(0,24,0);
foreach($rows as $r){if($r['check_in']!==''){$cards['Present']++;$cards[$r['late_minutes']>0?'Late arrivals':'On time']++;$hours[(int)substr($r['check_in'],11,2)]++;}$cards['Absent']+=$r['absent'];$cards['Overtime minutes']+=$r['overtime_minutes'];$d=$r['department']?:'Unassigned';$departments[$d]??=['total'=>0,'present'=>0];if(!in_array($r['status'],['Not started','Not active'],true)){$departments[$d]['total']++;if($r['check_in']!=='')$departments[$d]['present']++;}}
$cards['Pending requests']=(int)$pdo->query("SELECT COUNT(*) FROM hr_requests WHERE kind='regularisation' AND status='Pending'")->fetchColumn();?><div class="stats"><?php foreach($cards as $label=>$value):?><section class="card"><p class="eyebrow"><?=h($label)?></p><h2><?=h($value)?></h2></section><?php endforeach;?></div><section class="card"><h2>Check-ins by hour</h2><div class="attendance-hour-chart"><?php $max=max(1,max($hours));foreach($hours as $hour=>$count):?><div title="<?=sprintf('%02d:00 — %d check-ins',$hour,$count)?>"><span style="height:<?=max(2,(int)round($count/$max*120))?>px"></span><small><?=sprintf('%02d',$hour)?></small><small><?=$count?></small></div><?php endforeach;?></div></section><section class="card"><h2>Department attendance</h2><?php foreach($departments as $label=>$counts):$rate=$counts['total']?round($counts['present']/$counts['total']*100,1):0;?><p><?=h($label)?> · <?=$counts['present']?> / <?=$counts['total']?> · <?=$rate?>%</p><progress max="100" value="<?=$rate?>"><?=$rate?>%</progress><?php endforeach;?></section><?php
$rows=array_values(array_filter($rows,fn($r)=>$r['late_minutes']>0||$r['early_minutes']>0||in_array($r['status'],['Open','Absent'],true)));echo '<h2>Attendance exceptions</h2>';
elseif($grid):$dates=chr_dates($from,$to);$employees=[];foreach($rows as $r){$employees[$r['employee_id']]['name']=$r['name'];$employees[$r['employee_id']]['days'][$r['date']]=$r;}$codes=['Present'=>'P','Late'=>'LT','Absent'=>'A','Open'=>'IN','Half Day'=>'HD','Half Day Leave'=>'HL','Leave'=>'L','Holiday'=>'H','Week Off'=>'WO','Pending'=>'—','Unscheduled'=>'US','Not started'=>'NS','Not active'=>'NA','Review needed'=>'!'];?><section class="card"><p>P Present · LT Late · A Absent · IN Check-out pending · HD Half day · HL Half-day leave · L Leave · H Holiday · WO Week off · US Unscheduled</p><div class="table-scroll"><table class="directory"><thead><tr><th>Employee</th><?php foreach($dates as $date):?><th><?=substr($date,8)?></th><?php endforeach;?></tr></thead><tbody><?php foreach($employees as $employee):?><tr><th><?=h($employee['name'])?></th><?php foreach($dates as $date):$r=$employee['days'][$date]??null;?><td title="<?=h($r?$r['date'].' · '.$r['status'].' · '.$r['shift']:'Filtered out')?>"><?=h($r?($codes[$r['status']]??'?'):'—')?></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div></section><?php return;
elseif($page==='attendance_exceptions'):$rows=array_values(array_filter($rows,fn($r)=>$r['late_minutes']>0||$r['early_minutes']>0));
else:$rows=array_values(array_filter($rows,fn($r)=>$r['check_in']!==''&& (empty($_GET['source'])||$_GET['source']===$r['source'])));endif;
?><section class="card"><div class="table-scroll"><table class="directory"><thead><tr><?php foreach(['Employee','Department','Shift','Scheduled start','Scheduled end','Check-in','Check-out','Worked','Late','Early','Overtime','Source','Status'] as $label):?><th><?=h($label)?></th><?php endforeach;?></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="11">No matching records.</td></tr><?php endif;foreach($rows as $r):?><tr><td><?=h($r['name'])?></td><td><?=h($r['department'])?></td><td><?=h($r['shift'])?></td><td><?=h($r['scheduled_in']?:'—')?></td><td><?=h($r['scheduled_out']?:'—')?></td><td><?=h($r['check_in']?:'—')?></td><td><?=h($r['check_out']?:'—')?></td><?php foreach(['working_minutes','late_minutes','early_minutes','overtime_minutes'] as $key):?><td><?=h(chr_hours($r[$key]))?></td><?php endforeach;?><td><?=h($r['source'])?></td><td><?=h($r['status'])?></td></tr><?php endforeach;?></tbody></table></div></section>
