<?php
$grid=$page==='daily_work_status';$month=$_GET['month']??date('Y-m');$day=$_GET['date']??date('Y-m-d');
try{[$from,$to]=chr_report_range($grid?'monthly':'attendance',$_GET);$rows=chr_report($pdo,$from,$to,$_GET);}catch(InvalidArgumentException $e){echo '<div class="alert error">'.h($e->getMessage()).'</div>';return;}
if($grid){$attendanceSheet=true;require __DIR__.'/manual-view.php';require __DIR__.'/attendance-editor.php';}
if($page!=='attendance_dashboard'){?><form class="card att-filter" method="get"><?php chr_hidden('page',$page);if($grid)field('month','Month',['month'=>$month],'month',true);else field('date','Date',['date'=>$day],'date',true);chr_select('department_id','Department',$_GET['department_id']??'', [''=>'All departments']+$departmentOptions);chr_select('employee_id','Employee',$_GET['employee_id']??'', [''=>'All employees']+$historyEmployeeOptions);chr_select('shift_id','Shift',$_GET['shift_id']??'', [''=>'All shifts']+$shiftOptions);if($page==='punch_log')chr_select('source','Source',$_GET['source']??'',array_combine(['','Admin Manual','CSV Import','Biometric','Admin','Manual','Web','API','eSSL'],['All sources','Admin Manual','CSV Import','Biometric','Admin','Manual','Web','API','eSSL']));if($page==='punch_log'&&att_biometric_enabled($pdo)){$deviceChoices=[''=>'All devices'];foreach(chr_rows($pdo,'devices') as $device)$deviceChoices[$device['values']['device_code']]=$device['title'];chr_select('device_code','Device',$_GET['device_code']??'',$deviceChoices);}?><div class="att-filter-actions"><button class="button primary">Apply filters</button><?php if($grid&&can($pdo,$user,'attendance.reports')):?><button class="button" name="export" value="1">Export sheet</button><?php endif;?></div></form><?php }
if($page==='attendance_dashboard'):require __DIR__.'/dashboard-view.php';return;
elseif($grid):$dates=chr_dates($from,$to);$employees=[];foreach($rows as $r){$employees[$r['employee_id']]['name']=$r['name'];$employees[$r['employee_id']]['code']=$r['employee_code'];$employees[$r['employee_id']]['days'][$r['date']]=$r;}$codes=['Present'=>'P','Late'=>'LT','Absent'=>'A','Open'=>'IN','Half Day'=>'HD','Half Day Leave'=>'HL','Leave'=>'L','Holiday'=>'H','Week Off'=>'WO','Pending'=>'—','Unscheduled'=>'US','Not started'=>'NS','Not active'=>'NA','Review needed'=>'!'];?><section class="card"><div class="att-panel-heading"><h2><?=h(date('F Y',strtotime($from)))?> attendance</h2><span class="att-tag"><?=count($employees)?> employees</span></div><p>P Present · LT Late · A Absent · IN Check-out pending · HD Half day · HL Half-day leave · L Leave · H Holiday · WO Week off · US Unscheduled</p><div class="table-scroll attendance-table-scroll" tabindex="0" role="region" aria-label="Attendance records"><table class="directory" data-freeze-first="true"><thead><tr><th>Employee</th><?php foreach($dates as $date):?><th><?=substr($date,8)?></th><?php endforeach;?></tr></thead><tbody><?php if(!$employees):?><tr><td colspan="<?=count($dates)+1?>">No matching employees for this month.</td></tr><?php endif;foreach($employees as $employee):?><tr><th><?=h($employee['name'])?><small><?=h($employee['code'])?></small></th><?php foreach($dates as $date):$r=$employee['days'][$date]??null;?><td title="<?=h($r?$r['date'].' · '.$r['status'].' · '.$r['shift']:'Filtered out')?>"><?php $editable=$r&&isset($employeeOptions[$r['employee_id']])&&$date<=date('Y-m-d')&&can($pdo,$user,'attendance.manage');if($editable):$entry=['page'=>'daily_work_status','month'=>$month,'entry_employee'=>$r['employee_id'],'entry_date'=>$date];if($r['record_id'])$entry['edit']=$r['record_id'];?><a class="att-sheet-cell" href="?<?=h(http_build_query($entry))?>" aria-label="<?=h('Edit '.$employee['name'].' attendance for '.$date)?>"><?php endif;?><span class="sheet-status" data-status="<?=h($r['status']??'')?>"><?=h($r?($codes[$r['status']]??'?'):'—')?></span><?php if($editable):?></a><?php endif;?></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div></section><?php return;
elseif($page==='attendance_exceptions'):$rows=array_values(array_filter($rows,fn($r)=>$r['late_minutes']>0||$r['early_minutes']>0));
else:$rows=array_values(array_filter($rows,fn($r)=>$r['check_in']!==''&& (empty($_GET['source'])||$_GET['source']===$r['source'])));endif;
?><section class="card"><div class="table-scroll attendance-table-scroll" tabindex="0" role="region" aria-label="Attendance records"><table class="directory"><thead><tr><?php foreach(['Employee','Department','Shift','Scheduled start','Scheduled end','Check-in','Check-out','Worked','Late','Early','Overtime','Source','Devices','Status'] as $label):?><th><?=h($label)?></th><?php endforeach;?></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="11">No matching records.</td></tr><?php endif;foreach($rows as $r):?><tr><td><?=h($r['name'])?></td><td><?=h($r['department'])?></td><td><?=h($r['shift'])?></td><td><?=h(att_time_label($r['scheduled_in'],false,true))?></td><td><?=h(att_time_label($r['scheduled_out'],false,true))?></td><td><?=h(att_time_label($r['check_in'],false,true))?></td><td><?=h(att_time_label($r['check_out'],false,true))?></td><?php foreach(['working_minutes','late_minutes','early_minutes','overtime_minutes'] as $key):?><td><?=h(chr_hours($r[$key]))?></td><?php endforeach;?><td><?=h($r['source'])?></td><td><?=h($r['devices'])?></td><td><?=h($r['status'])?></td></tr><?php endforeach;?></tbody></table></div></section>

