<?php
function att_resolution_context(PDO $db):array {
 $ctx=['assignments'=>[],'shifts'=>[],'defaults'=>chr_rows($db,'shift_defaults'),'policies'=>chr_rows($db,'time_policies'),'department_history'=>[]];
 foreach(chr_rows($db,'shifts') as $r)$ctx['shifts'][(int)$r['id']]=$r;
 foreach(chr_rows($db,'roster') as $r)if($r['status']==='Active')$ctx['assignments'][(int)$r['employee_id']][]=$r;
 foreach(chr_rows($db,'department_history') as $r)$ctx['department_history'][(int)$r['employee_id']][]=$r;return $ctx;
}
function att_department(array $ctx,array $employee,string $day):int {
 $id=(int)($employee['department_id']??0);foreach($ctx['department_history'][(int)$employee['user_id']]??[] as $r)if(($r['values']['date']??'')>$day)$id=(int)$r['values']['before'];return $id;
}
function att_effective(array $r,string $day):bool{$d=$r['values'];return $r['status']==='Active'&&($d['from']??'1000-01-01')<=$day&&((($d['to']??null)?:'9999-12-31')>=$day);}
function att_resolve(array $ctx,array $employee,string $day):?array {
 $department=att_department($ctx,$employee,$day);$levels=['Employee'=>$ctx['assignments'][(int)$employee['user_id']]??[],'Department'=>[],'Company'=>[]];
 foreach($ctx['defaults']??[] as $r){$d=$r['values'];if(($d['scope']??'')==='Company')$levels['Company'][]=$r;elseif(($d['scope']??'')==='Department'&&(int)($d['department_id']??0)===$department)$levels['Department'][]=$r;}
 foreach($levels as $source=>$rows){$matches=array_values(array_filter($rows,fn($r)=>att_effective($r,$day)));if(count($matches)>1)throw new InvalidArgumentException('Overlapping '.$source.' shift assignments. Correct the assignment history.');if(!$matches)continue;$a=$matches[0];$shift=$ctx['shifts'][(int)($a['values']['shift_id']??0)]??null;if(!$shift)continue;$shift['values']=$a['values']['shift_snapshot']??$shift['values'];$shift['assignment_source']=$source;$shift['assignment_id']=$a['id'];
  $policies=['Shift'=>[],'Default'=>[]];foreach($ctx['policies']??[] as $p){$v=$p['values'];if(!att_effective($p,$day))continue;if((int)($v['shift_id']??0)===(int)$shift['id'])$policies['Shift'][]=$p;elseif(!empty($v['default']))$policies['Default'][]=$p;}
  foreach($policies as $rows){if(count($rows)>1)throw new InvalidArgumentException('Overlapping time policies. Correct policy effective dates.');if(!$rows)continue;$p=$rows[0];$v=$p['values'];$shift['values']['grace']=!empty($v['apply_in'])?$v['allowed_minutes']:0;$shift['values']['early_grace']=!empty($v['apply_out'])?$v['allowed_minutes']:0;foreach(['minimum_hours','half_day_hours','required_hours','overtime_rule'] as $k)$shift['values'][$k]=$v[$k];$shift['values']['policy_id']=$p['id'];$shift['values']['policy_name']=$p['title'];break;}return $shift;
 }return null;
}
function att_save_default(PDO $db,array $actor,array $in):int {
 if(!can($db,$actor,'shifts.manage'))throw new InvalidArgumentException('Shift management is not permitted.');$scope=$in['scope']??'';if(!in_array($scope,['Company','Department'],true))throw new InvalidArgumentException('Select Company or Department.');$department=$scope==='Department'?(int)($in['department_id']??0):null;if($department){$q=$db->prepare('SELECT id FROM departments WHERE id=? AND active=1');$q->execute([$department]);if(!$q->fetchColumn())throw new InvalidArgumentException('Select an active department.');}elseif($scope==='Department')throw new InvalidArgumentException('Select a department.');
 $db->beginTransaction();try{chr_lock($db);$id=(int)($in['id']??0);$old=$id?chr_record($db,'shift_defaults',$id):null;$from=chr_date((string)($in['from']??''));$to=fdate($in,'to');$shift=chr_record($db,'shifts',(int)($in['shift_id']??0));if(!$shift||($shift['status']!=='Active'&&(!$old||(int)$old['values']['shift_id']!==(int)$shift['id'])))throw new InvalidArgumentException('Select an active shift.');if($to&&$to<$from)throw new InvalidArgumentException('End date precedes start date.');$active=!empty($in['active']);$v=['scope'=>$scope,'department_id'=>$department,'from'=>$from,'to'=>$to,'shift_id'=>(int)$shift['id'],'reason'=>ftext($in,'reason',2000,true),'shift_snapshot'=>($old&&(int)$old['values']['shift_id']===(int)$shift['id']?($old['values']['shift_snapshot']??$shift['values']):$shift['values'])];
 if($old&&$old['values']['from']<=date('Y-m-d')){foreach(['scope','department_id','from','shift_id'] as $key)if((string)($old['values'][$key]??'')!==(string)($v[$key]??''))throw new InvalidArgumentException('Preserve started assignments. End this assignment and add a new one.');if(!$active||($to&&$to<date('Y-m-d')&&$to!==($old['values']['to']??null)))throw new InvalidArgumentException('Do not remove past assignment history.');}
 if($active)foreach(chr_rows($db,'shift_defaults') as $r){$d=$r['values'];if((int)$r['id']!==$id&&$r['status']==='Active'&&($d['scope']??'')===$scope&&(int)($d['department_id']??0)===(int)$department&&($d['from']??'9999')<=($to?:'9999-12-31')&&(($d['to']??null)?:'9999-12-31')>=$from)throw new InvalidArgumentException('A default shift already covers these dates. End it before adding another.');}
 $id=att_record_write($db,$actor,'shift_defaults',$in,$v,null,$active?'Active':'Inactive');$db->commit();return $id;}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
}
function att_save_policy(PDO $db,array $actor,array $in):int {
 if(!can($db,$actor,'time_policies.manage'))throw new InvalidArgumentException('Time policy management is not permitted.');$shift=(int)($in['shift_id']??0);$default=!empty($in['default']);if(($shift>0)===$default)throw new InvalidArgumentException('Choose an assigned shift or a company default policy.');if($shift&&!chr_record($db,'shifts',$shift))throw new InvalidArgumentException('Shift not found.');$v=['shift_id'=>$shift,'default'=>$default,'from'=>chr_date((string)($in['from']??'')),'to'=>fdate($in,'to'),'apply_in'=>!empty($in['apply_in']),'apply_out'=>!empty($in['apply_out']),'allowed_minutes'=>chr_number($in,'allowed_minutes',240)];foreach(['minimum_hours','half_day_hours','required_hours'] as $k)$v[$k]=chr_number($in,$k,24);if($v['required_hours']<=0||$v['minimum_hours']>$v['half_day_hours']||$v['half_day_hours']>$v['required_hours'])throw new InvalidArgumentException('Use minimum ≤ half-day ≤ full-day hours, with a positive full day.');$v['overtime_rule']=$in['overtime_rule']??'';if(!in_array($v['overtime_rule'],['After shift end','After required hours','After both'],true))throw new InvalidArgumentException('Choose an overtime rule.');if($v['to']&&$v['to']<$v['from'])throw new InvalidArgumentException('Invalid policy dates.');
 $db->beginTransaction();try{chr_lock($db);$id=(int)($in['id']??0);$old=$id?chr_record($db,'time_policies',$id):null;$active=!empty($in['active']);if($old&&$old['values']['from']<=date('Y-m-d')){foreach($v as $k=>$value)if($k!=='to'&&$value!=($old['values'][$k]??null))throw new InvalidArgumentException('Started policies retain their rules. End this policy and add a new one.');if(!$active||($v['to']&&$v['to']<date('Y-m-d')&&$v['to']!==($old['values']['to']??null)))throw new InvalidArgumentException('Preserve past policy dates.');}
 if($active)foreach(chr_rows($db,'time_policies') as $r){$d=$r['values'];if((int)$r['id']!==$id&&$r['status']==='Active'&&(int)($d['shift_id']??0)===$shift&&(!empty($d['default']))===$default&&($d['from']??'9999')<=($v['to']?:'9999-12-31')&&(($d['to']??null)?:'9999-12-31')>=$v['from'])throw new InvalidArgumentException('This scope already has a policy for these dates.');}
 $id=att_record_write($db,$actor,'time_policies',$in,$v,null,$active?'Active':'Inactive');$db->commit();return $id;}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
}
