<?php if(!att_ready($pdo)):?><section class="card"><h2>Enable the attendance upgrade</h2><p>Add attendance configuration and bridge support to your existing records.</p><?php if($user['role']==='super_admin'):?><form method="post"><?php ftoken();chr_hidden('action','att_install');?><button class="button primary">Enable Attendance Upgrade</button></form><?php endif;?></section><?php return;endif;
if(in_array($page,['attendance_settings','biometric_integration'],true)):
$cfg=att_config($pdo);$record=chr_rows($pdo,'attendance_settings')[0]??null;
?><?php if($page==='attendance_settings'):?><section class="card"><h2>Attendance mode</h2><p>Manual attendance always remains available. Device menus and bridge APIs are enabled together by this setting.</p><?php if(can($pdo,$user,'settings.edit')):?><form method="post" class="form-grid core-form"><?php ftoken();chr_hidden('action','att_settings');chr_hidden('version',$record['version']??0);choose('mode','Attendance mode',$cfg,['Manual Attendance','Manual + Biometric']);chr_checkbox('biometric_enabled','Enable biometric attendance',!empty($cfg['biometric_enabled']));?><div class="full"><button class="button primary">Save attendance settings</button></div></form><?php endif;fbadge(!empty($cfg['biometric_enabled'])?'Biometric enabled':'Biometric off',!empty($cfg['biometric_enabled']));?></section>
<?php endif;if($page==='biometric_integration'):?><section class="card"><h2>Biometric setup</h2><ol><li>Enable Manual + Biometric in <a class="link" href="?page=attendance_settings">Attendance Mode</a>.</li><li>Register the office device and configure the Windows bridge.</li><li>Map each device user ID to the correct employee.</li><li>Check sync history and resolve unmapped punches.</li></ol><p>The office Windows bridge reads your LAN device, queues punches locally and sends them to the HRMS HTTPS API. The hosting server never connects directly to the device’s private IP.</p><p>Register a device, generate its dedicated token, then configure the bridge on the office computer. MySQL and administrator credentials are never required by the bridge.</p><?php if(att_biometric_enabled($pdo)):?><a class="button primary" href="?page=devices">Manage devices</a><?php endif;?></section><?php endif;
elseif($page==='attendance_requests'):require __DIR__.'/requests-view.php';
elseif($page==='company_calendar'):require __DIR__.'/calendar-view.php';
elseif($page==='shift_defaults'):require __DIR__.'/defaults-view.php';
elseif($page==='time_policies'):require __DIR__.'/policies-view.php';
elseif(in_array($page,['attendance_dashboard','daily_work_status','punch_log','attendance_exceptions'],true)):require __DIR__.'/reports-view.php';
elseif(in_array($page,['devices','mapping','sync','raw_logs'],true)):require __DIR__.'/devices-view.php';endif;
