<?php
if(PHP_SAPI!=='cli'||getenv('DB_NAME')!=='peopleflow_ci')exit('Disposable CI database only.');
require dirname(__DIR__).'/auth.php';require dirname(__DIR__).'/includes/core-hr/service.php';
set_error_handler(function($severity,$message,$file,$line){throw new ErrorException($message,0,$severity,$file,$line);});
function check(bool $ok,string $message):void {if(!$ok)throw new RuntimeException($message);}
function blocked(callable $fn,string $label):void {$caught=false;try{$fn();}catch(InvalidArgumentException $e){$caught=true;}check($caught,$label);}
$pdo=db();$admin=['id'=>1,'role'=>'super_admin'];$viewer=['id'=>3,'role'=>'employee'];
$tables=['users','employees','departments','designations','roles','role_permissions','user_roles','company_settings','hr_records','hr_requests','hr_files','hr_media'];$before=[];foreach($tables as $t)$before[$t]=$pdo->query('SELECT * FROM '.$t)->fetchAll(PDO::FETCH_ASSOC);
chr_install($pdo);chr_install($pdo);foreach($tables as $t)check($before[$t]===$pdo->query('SELECT * FROM '.$t)->fetchAll(PDO::FETCH_ASSOC),'Migration altered existing '.$t);
check((int)$pdo->query("SELECT COUNT(*) FROM hr_migrations WHERE name='005-core-hr'")->fetchColumn()===1,'Repeated migration marker');
$employee=(int)$pdo->query("SELECT id FROM users WHERE username='phase.tester'")->fetchColumn();check($employee>0,'Missing fixture employee');
$shiftInput=['title'=>'CI night','code'=>'CI-NIGHT','start'=>'22:00','end'=>'06:00','required_hours'=>7.5,'half_day_hours'=>4,'grace'=>10,'early_grace'=>5,'break_minutes'=>30,'overtime_rule'=>'After both','week_off'=>[7],'active'=>1];
$shift=chr_save_config($pdo,$admin,'shifts',$shiftInput);$rules=chr_record($pdo,'shifts',$shift)['values'];$metric=chr_calculate('2026-01-05','2026-01-05 22:20:00','2026-01-06 07:00:00',$rules);check($metric['working_minutes']===490&&$metric['late_minutes']===20&&$metric['early_minutes']===0&&$metric['overtime_minutes']===40,'Overnight metrics wrong');
$metric=chr_calculate('2026-01-05','2026-01-05 22:05:00','2026-01-06 05:30:00',$rules);check($metric['late_minutes']===0&&$metric['early_minutes']===30&&$metric['overtime_minutes']===0,'Grace or early leaving wrong');
blocked(fn()=>chr_datetime('2026-02-30T09:00'),'Invalid datetime accepted');blocked(fn()=>chr_calculate('2026-01-05','2026-01-05 22:00','2026-01-05 21:00',$rules),'Negative duration accepted');
$roster=chr_save_config($pdo,$admin,'roster',['title'=>'CI assignment','employee_id'=>$employee,'shift_id'=>$shift,'from'=>'2026-01-01','active'=>1]);
blocked(fn()=>chr_save_config($pdo,$admin,'roster',['title'=>'Overlap','employee_id'=>$employee,'shift_id'=>$shift,'from'=>'2026-01-10','active'=>1]),'Overlapping roster accepted');
chr_save_config($pdo,$admin,'shifts',array_merge($shiftInput,['id'=>$shift,'version'=>1,'start'=>'21:00']));check(chr_assignment($pdo,$employee,'2026-01-05')['values']['start']==='22:00','Assignment historical rules changed');
blocked(fn()=>chr_save_config($pdo,$admin,'shifts',array_merge($shiftInput,['id'=>$shift,'version'=>1])),'Stale shift write accepted');blocked(fn()=>chr_delete_config($pdo,$admin,'shifts',$shift),'Assigned shift deleted');
$holiday=chr_save_config($pdo,$admin,'holidays',['title'=>'CI holiday','date'=>'2026-01-07','holiday_type'=>'Company Holiday','active'=>1]);
$policy=chr_save_config($pdo,$admin,'leave_policy',['title'=>'CI leave','type'=>'CI','annual_days'=>2,'carry_forward'=>1,'paid'=>1,'active'=>1]);
$balance=chr_save_config($pdo,$admin,'balances',['title'=>'CI allocation','employee_id'=>$employee,'year'=>2026,'type'=>'CI','allocation'=>2,'carry'=>0,'active'=>1]);
$leaveInput=['employee_id'=>$employee,'category'=>'CI','start_date'=>'2026-01-07','end_date'=>'2026-01-08','day_part'=>'Full Day','details'=>'CI request'];$leave=chr_create_leave($pdo,$admin,$leaveInput);chr_review_leave($pdo,$admin,$leave,'Approved');check(chr_used($pdo,$employee,'CI',2026)===1.0,'Holiday charged as leave');
$half=array_merge($leaveInput,['start_date'=>'2026-01-09','end_date'=>'2026-01-09','day_part'=>'First Half']);$first=chr_create_leave($pdo,$admin,$half);chr_review_leave($pdo,$admin,$first,'Approved');$second=chr_create_leave($pdo,$admin,array_merge($half,['day_part'=>'Second Half']));chr_review_leave($pdo,$admin,$second,'Approved');check(chr_used($pdo,$employee,'CI',2026)===2.0,'Half-day balance incorrect');
$duplicate=chr_create_leave($pdo,$admin,$half);blocked(fn()=>chr_review_leave($pdo,$admin,$duplicate,'Approved'),'Overlapping half-day approved');chr_review_leave($pdo,$admin,$duplicate,'Rejected');
$next=chr_create_leave($pdo,$admin,array_merge($leaveInput,['start_date'=>'2026-01-12','end_date'=>'2026-01-12']));blocked(fn()=>chr_review_leave($pdo,$admin,$next,'Approved'),'Balance overspend approved');chr_review_leave($pdo,$admin,$leave,'Cancelled');check(chr_used($pdo,$employee,'CI',2026)===1.0,'Cancellation did not release balance');chr_review_leave($pdo,$admin,$next,'Approved');
blocked(fn()=>chr_create_leave($pdo,$admin,array_merge($half,['start_date'=>'2026-01-11','end_date'=>'2026-01-11'])),'Weekly off charged');
blocked(fn()=>chr_save_config($pdo,$admin,'balances',['id'=>$balance,'version'=>1,'title'=>'Lower allocation','employee_id'=>$employee,'year'=>2026,'type'=>'CI','allocation'=>1,'carry'=>0,'active'=>1]),'Allocation below usage accepted');
$attendanceInput=['employee_id'=>$employee,'attendance_date'=>'2026-01-05','check_in'=>'2026-01-05T22:20','source'=>'Admin','notes'=>'CI check-in'];$attendance=chr_save_attendance($pdo,$admin,$attendanceInput);$r=$pdo->query('SELECT * FROM hr_attendance WHERE id='.$attendance)->fetch(PDO::FETCH_ASSOC);check($r['status']==='Open','Open punch incorrectly complete');
chr_save_attendance($pdo,$admin,array_merge($attendanceInput,['id'=>$attendance,'version'=>1,'check_out'=>'2026-01-06T07:00','notes'=>'CI check-out']));$r=$pdo->query('SELECT * FROM hr_attendance WHERE id='.$attendance)->fetch(PDO::FETCH_ASSOC);check((int)$r['working_minutes']===490&&(int)$r['late_minutes']===20,'Saved attendance calculation wrong');
blocked(fn()=>chr_save_attendance($pdo,$admin,array_merge($attendanceInput,['id'=>$attendance,'version'=>1,'notes'=>'stale'])),'Stale attendance write accepted');blocked(fn()=>chr_save_attendance($pdo,$viewer,$attendanceInput),'Attendance permission bypass');blocked(fn()=>chr_create_leave($pdo,$viewer,$leaveInput),'Leave creation permission bypass');blocked(fn()=>chr_review_leave($pdo,$viewer,$next,'Cancelled'),'Leave cancellation permission bypass');
$rows=chr_report($pdo,'2026-01-05','2026-01-12',['employee_id'=>$employee]);$byDay=array_column($rows,null,'date');check($byDay['2026-01-07']['status']==='Holiday'&&$byDay['2026-01-07']['absent']===0,'Holiday absent');check($byDay['2026-01-11']['status']==='Week Off','Week off missing');check($byDay['2026-01-09']['status']==='Leave','Two halves not merged');check($byDay['2026-01-12']['status']==='Leave','Approved leave not reflected');check($byDay['2026-01-06']['status']==='Absent','Scheduled absence missing');$monthly=chr_monthly($rows);check(count($monthly)===1&&$monthly[0]['working_minutes']===490&&$monthly[0]['leave']===2,'Monthly aggregation wrong');
// Legacy calendar requests remain readable and are not reinterpreted as shift days.
$legacy=$pdo->query("SELECT * FROM hr_requests WHERE kind='leave' AND status='Approved' AND id NOT IN (SELECT request_id FROM hr_leave_details) LIMIT 1")->fetch(PDO::FETCH_ASSOC);if($legacy)check(count(chr_request_days($pdo,$legacy))===(new DateTimeImmutable($legacy['start_date']))->diff(new DateTimeImmutable($legacy['end_date']))->days+1,'Legacy day semantics changed');
file_put_contents('/tmp/core-hr-fixture.json',json_encode(compact('employee','shift','roster','holiday','policy','balance','attendance','next')));
echo "PASS: additive migration preservation, shifts, overnight calculations, immutable snapshots, holiday/week-off exclusion, half-day approvals, overlaps, balances, cancellation, attendance edits, reports and permission guards.\n";
