<?php
if(PHP_SAPI!=='cli'||getenv('DB_NAME')!=='peopleflow_ci')exit('Disposable CI database only.');
require dirname(__DIR__).'/auth.php';require dirname(__DIR__).'/includes/foundation/migrate.php';require dirname(__DIR__).'/includes/foundation/employees.php';require dirname(__DIR__).'/includes/foundation/recovery.php';
function verify(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
function rejects(callable $fn,string $label):void{$bad=false;try{$fn();}catch(InvalidArgumentException $e){$bad=true;}verify($bad,$label);}
$pdo=db();$admin=['id'=>1,'role'=>'super_admin'];foundation_migrate($pdo);foundation_migrate($pdo);
verify((int)$pdo->query('SELECT COUNT(*) FROM employees')->fetchColumn()===2,'Existing employee backfill failed');verify((int)$pdo->query('SELECT COUNT(*) FROM roles')->fetchColumn()===6,'Default roles duplicated');
$pdo->exec("INSERT INTO departments(name) VALUES('Engineering'),('Operations')");$department=(int)$pdo->query("SELECT id FROM departments WHERE name='Engineering'")->fetchColumn();$other=(int)$pdo->query("SELECT id FROM departments WHERE name='Operations'")->fetchColumn();
$pdo->prepare('INSERT INTO designations(name,department_id) VALUES(?,?)')->execute(['Engineer',$department]);$designation=(int)$pdo->lastInsertId();$role=(int)$pdo->query("SELECT id FROM roles WHERE slug='employee'")->fetchColumn();
$input=['first_name'=>'Phase','last_name'=>'Tester','username'=>'phase.tester','email'=>'phase@example.test','department_id'=>$department,'designation_id'=>$designation,'role_id'=>$role,'joining_date'=>'2026-01-01','birth_date'=>'1990-02-01','employment_type'=>'Full Time','employment_status'=>'Active','employee_code'=>'CI-001'];
$id=save_employee($pdo,$admin,$input,[]);$employee=foundation_employee($pdo,$id);verify($employee['department_name']==='Engineering'&&$employee['username']==='phase.tester','Employee create failed');
$u=$pdo->query('SELECT * FROM users WHERE id='.$id)->fetch(PDO::FETCH_ASSOC);verify(password_verify('User@123',$u['password_hash'])&&(int)$u['must_change_password']===1,'Initial credentials failed');
$edit=array_merge($input,['id'=>$id,'version'=>$employee['version'],'mobile'=>'9876543210']);save_employee($pdo,$admin,$edit,[]);rejects(fn()=>save_employee($pdo,$admin,$edit,[]),'Stale profile write accepted');
rejects(fn()=>save_employee($pdo,$admin,array_merge($input,['department_id'=>$other]),[]),'Cross-department designation accepted');rejects(fn()=>save_employee($pdo,$admin,array_merge($input,['birth_date'=>'2026-02-30']),[]),'Invalid date accepted');
$rows=[['name'=>'Import Example','designation'=>'Analyst','phone'=>'1234567890','birth_date'=>'1995-05-02','blood_group'=>'B+','emergency_contact'=>'1234567891','source_status'=>'Pending']];[$created,$skipped]=import_foundation($pdo,$admin,$rows);verify($created===1&&$skipped===0,'Employee import failed');[$created,$skipped]=import_foundation($pdo,$admin,$rows);verify($created===0&&$skipped===1,'Import not idempotent');
$import=$pdo->query("SELECT u.*,e.employee_code,e.department_id,e.joining_date FROM users u JOIN employees e ON u.id=e.user_id WHERE u.username='import.example'")->fetch(PDO::FETCH_ASSOC);verify($import['employee_code']===null&&$import['email']===null&&$import['department_id']===null&&$import['joining_date']===null,'Import invented data');
verify(can($pdo,$admin,'roles.delete')&&!can($pdo,['id'=>2,'role'=>'employee'],'employees.edit'),'Default access failed');
$pdo->exec("INSERT INTO roles(name,slug) VALUES('Viewer','ci-viewer')");$viewer=(int)$pdo->lastInsertId();$pdo->exec("INSERT INTO role_permissions(role_id,permission_id) SELECT $viewer,id FROM permissions WHERE code IN ('dashboard.view','employees.view')");$pdo->prepare('UPDATE user_roles SET role_id=? WHERE user_id=?')->execute([$viewer,3]);verify(can($pdo,['id'=>3,'role'=>'employee'],'employees.view')&&!can($pdo,['id'=>3,'role'=>'employee'],'employees.edit'),'Custom permission failed');
$pdo->exec('UPDATE roles SET active=0 WHERE id='.$viewer);verify(!can($pdo,['id'=>3,'role'=>'employee'],'employees.view'),'Inactive role grants access');$pdo->exec('UPDATE roles SET active=1 WHERE id='.$viewer);
$edit=foundation_employee($pdo,$id);$edit['role_id']=$viewer;rejects(fn()=>save_employee($pdo,['id'=>2,'role'=>'employee'],$edit,[]),'Unauthorized role assignment accepted');
$pdo->exec('UPDATE users SET must_change_password=0 WHERE id='.$id);putenv('APP_ENV=testing');request_recovery($pdo,'phase.tester','test-address');$mail=json_decode(file_get_contents('/tmp/peopleflow-reset-test.json'),true);verify($mail['email']==='phase@example.test','Recovery email target mismatch');
$hash=$pdo->query('SELECT token_hash FROM password_resets ORDER BY id DESC LIMIT 1')->fetchColumn();verify($hash===hash('sha256',$mail['token']),'Reset token not hashed');apply_recovery($pdo,$mail['token'],'Changed-CI-Password-2026');rejects(fn()=>apply_recovery($pdo,$mail['token'],'Changed-CI-Again-2026'),'Token replay accepted');
$u=$pdo->query('SELECT * FROM users WHERE id='.$id)->fetch(PDO::FETCH_ASSOC);verify((int)$u['session_version']===1&&password_verify('Changed-CI-Password-2026',$u['password_hash']),'Reset did not revoke sessions');
$expired=bin2hex(random_bytes(32));$pdo->prepare('INSERT INTO password_resets(user_id,token_hash,expires_at) VALUES(?,?,DATE_SUB(NOW(),INTERVAL 1 MINUTE))')->execute([$id,hash('sha256',$expired)]);rejects(fn()=>apply_recovery($pdo,$expired,'Changed-CI-Password-2026'),'Expired token accepted');
// Stable credentials for HTTP tests; never run against a real database.
$pdo->prepare('UPDATE users SET password_hash=? WHERE id=?')->execute([password_hash('User@123',PASSWORD_DEFAULT),$id]);
echo "PASS: additive migration, employee CRUD, optimistic locking, department validation, private import, configurable permissions, password recovery, single-use tokens and session revocation.\n";
