<?php
$salaryEmployee=(int)($_GET['employee_id']??0);$structures=[''=>'Choose salary structure'];foreach(chr_rows($pdo,'pay_structure') as $r)if($r['status']==='Active')$structures[$r['id']]=$r['title'].' · '.$r['values']['effective_from'];
$designationOptions=[''=>'All designations'];foreach($pdo->query('SELECT id,name FROM designations ORDER BY name') as $designation)$designationOptions[$designation['id']]=$designation['name'];
?>
<form method="get" class="card pay-card pay-toolbar"><?php pay_hidden('page','employee_salary');pay_select('employee_id','Employee',$salaryEmployee,$employeeOptions);pay_select('department_id','Department',$_GET['department_id']??'',$departmentOptions);pay_select('designation_id','Designation',$_GET['designation_id']??'',$designationOptions);pay_select('structure_id','Salary structure',$_GET['structure_id']??'',[''=>'All structures']+array_diff_key($structures,[''=>true]));pay_select('salary_status','Status',$_GET['salary_status']??'',[''=>'All periods','Current'=>'Current','Future'=>'Future','Ended'=>'Ended']);?><button class="button primary">View salary history</button></form>
<?php if(can($pdo,$user,'payroll.salary.manage')):
$input=['employee_id'=>$salaryEmployee,'effective_from'=>date('Y-m-01'),'salary_basis'=>'Monthly Gross'];$preview=$_SESSION['pay_preview']??null;if($preview&&$preview['actor']===$user['id'])$input=$preview['input'];
?>
<details class="card pay-card" <?=($salaryEmployee||$preview)?'open':''?>><summary>Assign or revise salary</summary><?php pay_form('pay_preview');?><div class="pay-grid"><?php pay_select('employee_id','Employee',$input['employee_id']??'',$employeeOptions);pay_select('structure_id','Salary structure',$input['structure_id']??'',$structures);choose('salary_basis','Salary input',$input,['Monthly Gross','Annual CTC']);pay_text('salary_amount','Amount',$input,'text',true);pay_text('effective_from','Effective from',$input,'date',true);pay_text('effective_to','Effective to (optional)',$input,'date');pay_text('employee_ot_rate','Custom employee hourly OT rate',$input);pay_text('bank_last4','Bank account last 4 characters',$input);pay_text('pan_last4','PAN last 4 characters',$input);?></div>
<details><summary>Manual fixed component amounts</summary><div class="pay-grid"><?php $shown=[];foreach(chr_rows($pdo,'pay_component') as $c){$v=$c['values'];if($v['calculation']!=='Manual'||$v['section']==='Variable'||isset($shown[$v['code']]))continue;$shown[$v['code']]=true;pay_text('manual['.$v['code'].']',$c['title'].' ('.$v['code'].')',['manual['.$v['code'].']'=>$input['manual'][$v['code']]??'0']);}?></div></details>
<?php pay_text('reason','Reason for assignment / revision',$input,'text',true);pay_text('notes','Notes',$input);?><div class="pay-actions"><button class="button primary">Preview salary breakup</button></div></form></details>
<?php if($preview&&$preview['actor']===$user['id']):$p=$preview['preview'];?><section class="card pay-card"><h2>Salary preview · <?=h($p['employee']['name'])?></h2><p><?=h($p['structure_name'].' · Effective '.$p['effective_from'])?> · <?=h(($p['employee']['department_name']??'—').' / '.($p['employee']['designation_name']??'—'))?></p><?php pay_breakup_table($p['breakup']['components']);?><p><strong>Monthly gross: <?=pay_amount($p['breakup']['gross'])?> · Monthly net: <?=pay_amount($p['breakup']['net'])?> · Annual CTC: <?=pay_amount($p['breakup']['annual_ctc'])?></strong></p><?php pay_form('pay_assign');foreach($preview['input'] as $key=>$value)if(!in_array($key,['action','csrf','confirm'],true))pay_hidden($key,$value);pay_check('confirm','I reviewed this salary breakup and effective period',[]);?><div class="pay-actions"><button class="button primary">Save salary revision</button></div></form></section><?php endif;endif;?>
<?php
$sql='SELECT s.*,u.name,e.employee_code,d.name department_name,j.name designation_name FROM hr_salary_assignments s JOIN users u ON u.id=s.employee_id JOIN employees e ON e.user_id=s.employee_id LEFT JOIN departments d ON d.id=e.department_id LEFT JOIN designations j ON j.id=e.designation_id WHERE 1=1';$args=[];if($salaryEmployee){$sql.=' AND s.employee_id=?';$args[]=$salaryEmployee;}
foreach(['department_id'=>'e.department_id','designation_id'=>'e.designation_id','structure_id'=>'s.structure_id','assignment'=>'s.id'] as $filter=>$column)if(!empty($_GET[$filter])){$sql.=' AND '.$column.'=?';$args[]=(int)$_GET[$filter];}
$status=$_GET['salary_status']??'';if($status==='Current'){$sql.=' AND s.effective_from<=? AND (s.effective_to IS NULL OR s.effective_to>=?)';$args[]=date('Y-m-d');$args[]=date('Y-m-d');}elseif($status==='Future'){$sql.=' AND s.effective_from>?';$args[]=date('Y-m-d');}elseif($status==='Ended'){$sql.=' AND s.effective_to<?';$args[]=date('Y-m-d');}$q=$pdo->prepare($sql.' ORDER BY s.effective_from DESC,s.id DESC LIMIT 500');$q->execute($args);
?>
<section class="card pay-card"><h2>Salary revision history</h2><?php if(isset($_GET['assignment'])):?><div class="pay-actions"><button class="button" onclick="window.print()">Print salary breakup</button></div><?php endif;?><p class="pay-muted">Latest 500 revisions. Select an employee to narrow the history.</p><div class="pay-table"><table><thead><tr><th>Employee</th><th>Department / designation</th><th>Structure</th><th>Status</th><th>Effective period</th><th>Monthly gross</th><th>Annual CTC</th><th>Reason</th><th>Snapshot</th></tr></thead><tbody><?php foreach($q as $r):$s=json_decode($r['snapshot'],true);?><tr><td><?=h($r['name'].' · '.$r['employee_code'])?></td><td><?=h(($r['department_name']??'—').' / '.($r['designation_name']??'—'))?></td><td><?=h($s['structure_name'])?></td><td><?=h($r['effective_from']>date('Y-m-d')?'Future':($r['effective_to']&&$r['effective_to']<date('Y-m-d')?'Ended':'Current'))?></td><td><?=h($r['effective_from'].' → '.($r['effective_to']?:'Open'))?></td><td><?=pay_amount((int)$r['monthly_gross'])?></td><td><?=pay_amount((int)$r['annual_ctc'])?></td><td><?=h($r['reason'])?></td><td><a href="?page=employee_salary&assignment=<?=$r['id']?>">Open salary detail</a><details <?=isset($_GET['assignment'])?'open':''?>><summary>View saved breakup</summary><p><?=h($s['structure_name'])?></p><?php pay_breakup_table($s['breakup']['components']);?></details></td></tr><?php endforeach;?></tbody></table></div></section>
<?php if($user['role']==='super_admin'):?><p><a href="?page=salary">Previous salary records</a></p><?php endif;?>
