<?php
$module=$configModules[$page];$records=chr_rows($pdo,$module);$editing=null;foreach($records as $record)if((int)$record['id']===(int)($_GET['revision']??0)){$editing=$record;break;}
$v=$editing?$editing['values']:[];$v['title']=$editing['title']??$pages[$page][0];$v['active']=$editing?$editing['status']==='Active':true;
if(!$editing){$v['effective_from']=date('Y-m-01');if($module==='pay_settings')$v+=pay_setting_defaults();if($module==='pay_payslip')$v+=pay_slip_defaults();if($module==='pay_structure')$v+=['variable_cap'=>'0'];if($module==='pay_statutory')$v+=['employee_value'=>'0','employer_value'=>'0','basis'=>'GROSS','method'=>'Percentage'];if($module==='pay_component')$v+=['category'=>'Earning','calculation'=>'Fixed','section'=>'Fixed','basis'=>'GROSS','value'=>'0','visible'=>true,'include_gross'=>true,'include_ctc'=>true];}
else{$v['effective_from']=date('Y-m-d');$v['effective_to']='';}
?>
<p class="pay-muted">Changes create dated revisions. Existing salary assignments and finalized payroll retain their snapshots. To change a saved code, open its latest revision below.</p>
<?php if(can($pdo,$user,'payroll.settings.manage')):?>
<details class="card pay-card" <?=($editing||!$records)?'open':''?>><summary><?=$editing?'Create a new revision':'Add configuration'?></summary>
<?php pay_form('pay_config',['module'=>$module,'previous_id'=>$editing['id']??0]);?>
<div class="pay-grid"><?php pay_text('title','Name',$v,'text',true);if(!in_array($module,['pay_settings','pay_payslip'],true))pay_text('code','Code',$v,'text',true);pay_text('effective_from','Effective from',$v,'date',true);pay_text('effective_to','Effective to (optional)',$v,'date');pay_check('active','Active',$v);?></div>
<?php if($module==='pay_component'):?>
<div class="pay-grid"><?php choose('category','Type',$v,['Earning','Deduction','Employer']);choose('section','Pay section',$v,['Fixed','Variable']);choose('calculation','Calculation',$v,['Fixed','Percentage','Formula','Manual','Balance']);pay_text('value','Fixed amount or percentage',$v);pay_text('basis','Percentage basis expression',$v);pay_text('formula','Formula (amount in currency units)',$v);foreach(['taxable'=>'Taxable','include_gross'=>'Included in gross','include_ctc'=>'Included in CTC','visible'=>'Visible on payslip'] as $k=>$label)pay_check($k,$label,$v);?></div>
<p class="pay-muted">Use component codes and GROSS with + − * / and parentheses. Example: BASIC * 0.40. Balance fills the remaining gross. Variable components use Manual calculation.</p>
<?php elseif($module==='pay_structure'):
$selected=array_column($v['components']??[],'record_id');?><fieldset><legend>Salary components</legend><div class="pay-grid"><?php foreach(chr_rows($pdo,'pay_component') as $c):?><label class="pay-check"><input type="checkbox" name="component_ids[]" value="<?=$c['id']?>" <?=in_array($c['id'],$selected)?'checked':''?>><?=h($c['title'].' · '.$c['values']['code'].' · '.$c['values']['effective_from'].' · '.$c['status'])?></label><?php endforeach;?></div></fieldset><div class="pay-grid"><?php pay_check('variable_enabled','Allow variable pay',$v);pay_text('variable_cap','Maximum variable pay (% of gross)',$v);?></div>
<?php elseif($module==='pay_statutory'):?><div class="pay-grid"><?php choose('scheme','Scheme',$v,['PF','ESI','TDS','Professional Tax','Other']);choose('method','Calculation',$v,['Percentage','Fixed']);pay_text('basis','Basis component code',['basis'=>$v['basis']??'GROSS'],'text',true);pay_text('employee_value','Employee rate (%) or fixed amount',$v);pay_text('employer_value','Employer rate (%) or fixed amount',$v);pay_text('wage_cap','Monthly wage cap (0 = no cap)',['wage_cap'=>pay_amount((int)($v['wage_cap']??0))]);pay_text('eligibility_limit','Gross eligibility limit (0 = no limit)',['eligibility_limit'=>pay_amount((int)($v['eligibility_limit']??0))]);?></div><p class="pay-muted">Enter the rules applicable to your company and effective period. No statutory rates are prefilled. TDS supports a configured amount/rate; individual tax declarations and annual tax computation are not calculated here.</p>
<?php elseif($module==='pay_settings'):?><div class="pay-grid"><?php
pay_text('closing_day','Closing day of following month (1–28)',$v,'number',true);
choose('proration','Salary proration',$v,['Calendar Days','Working Days','Fixed 30 Days']);pay_text('lop_basis','LOP basis component',$v,'text',true);choose('lop_days','LOP days',$v,['Absent + unpaid leave','Unpaid leave only']);
pay_check('ot_enabled','Enable overtime',$v);choose('ot_method','Overtime rate',$v,['Fixed Hourly Rate','Basic Salary Based','Gross Salary Based','Custom Employee Rate']);pay_text('ot_rate','Fixed hourly rate',$v);pay_text('ot_basis','Basic salary component code',$v);pay_text('hours_per_day','Hours per working day',$v);
pay_check('variable_enabled','Enable variable pay',$v);choose('rounding','Rounding',$v,['Paise','Nearest Rupee']);pay_check('approval_required','Require approval before finalization',$v);pay_check('auto_payslip','Publish payslips on finalization',$v);pay_text('currency','Currency code',$v,'text',true);choose('currency_position','Currency position',$v,['Before','After']);
?></div>
<?php else:?><div class="pay-grid"><?php foreach(['show_logo'=>'Show company logo','show_address'=>'Show company address','show_attendance'=>'Show attendance summary','show_bank'=>'Show masked bank suffix','show_pan'=>'Show masked PAN suffix'] as $k=>$label)pay_check($k,$label,$v);pay_hidden('mask_sensitive','1');pay_text('number_format','Payslip number format',$v,'text',true);pay_text('signatory','Authorized signatory',$v);pay_text('footer','Footer',$v);?></div><p class="pay-muted">Available placeholders: {YYYY}, {MM}, {ID}. Only the last four characters of sensitive details are stored.</p><?php endif;?>
<?php pay_text('description','Description / revision notes',$v);?><div class="pay-actions"><button class="button primary">Save dated revision</button><?php if($editing):?><a class="button" href="?page=<?=h($page)?>">Cancel</a><?php endif;?></div></form></details><?php endif;?>
<section class="card pay-card"><h3>Configuration history</h3><div class="pay-table"><table><thead><tr><th>Name</th><th>Code</th><th>Effective period</th><th>Status</th><th>Details</th><th></th></tr></thead><tbody>
<?php $latest=[];foreach($records as $r):$d=$r['values'];$isLatest=!isset($latest[$d['code']]);$latest[$d['code']]=true;?>
<tr><td><?=h($r['title'])?></td><td><?=h($d['code'])?></td><td><?=h($d['effective_from'].' → '.($d['effective_to']?:'Open'))?></td><td><?=h($r['status'])?></td><td><details><summary>View configuration</summary><pre class="pay-detail"><?=h(json_encode($d,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE))?></pre></details></td><td><?php if($isLatest&&can($pdo,$user,'payroll.settings.manage')):?><a href="?page=<?=h($page)?>&revision=<?=$r['id']?>">New revision</a><?php endif;?></td></tr>
<?php endforeach;if(!$records)echo '<tr><td colspan="6">No configuration saved yet.</td></tr>';?></tbody></table></div></section>
