CREATE TABLE IF NOT EXISTS hr_migrations (name VARCHAR(100) PRIMARY KEY, applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS roles (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE,
 slug VARCHAR(100) NOT NULL UNIQUE, description VARCHAR(1000) NOT NULL DEFAULT '',
 active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS permissions (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(100) NOT NULL UNIQUE, label VARCHAR(150) NOT NULL) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS role_permissions (role_id INT UNSIGNED NOT NULL, permission_id INT UNSIGNED NOT NULL, PRIMARY KEY(role_id,permission_id), FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE, FOREIGN KEY(permission_id) REFERENCES permissions(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS user_roles (user_id INT UNSIGNED PRIMARY KEY, role_id INT UNSIGNED NOT NULL, FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(role_id) REFERENCES roles(id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS departments (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(150) NOT NULL UNIQUE, code VARCHAR(40) NULL UNIQUE,
 description VARCHAR(2000) NOT NULL DEFAULT '', head_id INT UNSIGNED NULL, active BOOLEAN NOT NULL DEFAULT TRUE,
 source_record_id BIGINT UNSIGNED NULL UNIQUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(head_id) REFERENCES users(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS designations (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(150) NOT NULL, department_id INT UNSIGNED NULL,
 description VARCHAR(2000) NOT NULL DEFAULT '', active BOOLEAN NOT NULL DEFAULT TRUE, source_record_id BIGINT UNSIGNED NULL UNIQUE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(department_id) REFERENCES departments(id), INDEX designation_department(department_id,name)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS employees (
 user_id INT UNSIGNED PRIMARY KEY, employee_code VARCHAR(60) NULL UNIQUE,
 first_name VARCHAR(80) NOT NULL, middle_name VARCHAR(100) NOT NULL DEFAULT '', last_name VARCHAR(80) NOT NULL DEFAULT '',
 personal_email VARCHAR(190) NULL, mobile VARCHAR(40) NOT NULL DEFAULT '', alternate_phone VARCHAR(40) NOT NULL DEFAULT '',
 birth_date DATE NULL, gender VARCHAR(30) NOT NULL DEFAULT '', blood_group VARCHAR(10) NOT NULL DEFAULT '',
 department_id INT UNSIGNED NULL, designation_id INT UNSIGNED NULL, manager_id INT UNSIGNED NULL,
 joining_date DATE NULL, employment_type VARCHAR(30) NOT NULL DEFAULT 'Full Time', employment_status VARCHAR(30) NOT NULL DEFAULT 'Active',
 current_address VARCHAR(2000) NOT NULL DEFAULT '', permanent_address VARCHAR(2000) NOT NULL DEFAULT '',
 city VARCHAR(100) NOT NULL DEFAULT '', state VARCHAR(100) NOT NULL DEFAULT '', country VARCHAR(100) NOT NULL DEFAULT '', pin_code VARCHAR(20) NOT NULL DEFAULT '',
 emergency_name VARCHAR(150) NOT NULL DEFAULT '', emergency_phone VARCHAR(40) NOT NULL DEFAULT '', emergency_relationship VARCHAR(80) NOT NULL DEFAULT '',
 import_notes VARCHAR(2000) NOT NULL DEFAULT '', version INT UNSIGNED NOT NULL DEFAULT 1, deleted_at DATETIME NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(department_id) REFERENCES departments(id), FOREIGN KEY(designation_id) REFERENCES designations(id), FOREIGN KEY(manager_id) REFERENCES users(id),
 INDEX employee_status(employment_status,deleted_at), INDEX employee_department(department_id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS company_settings (
 id INT UNSIGNED PRIMARY KEY, name VARCHAR(150) NOT NULL, email VARCHAR(190) NOT NULL DEFAULT '', phone VARCHAR(40) NOT NULL DEFAULT '', website VARCHAR(250) NOT NULL DEFAULT '',
 address VARCHAR(2000) NOT NULL DEFAULT '', city VARCHAR(100) NOT NULL DEFAULT '', state VARCHAR(100) NOT NULL DEFAULT '', country VARCHAR(100) NOT NULL DEFAULT '', pin_code VARCHAR(20) NOT NULL DEFAULT '', timezone VARCHAR(100) NOT NULL DEFAULT 'Asia/Kolkata', updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS hr_media (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NULL, purpose ENUM('profile','company_logo') NOT NULL,
 mime VARCHAR(80) NOT NULL, content MEDIUMBLOB NOT NULL, uploaded_by INT UNSIGNED NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(uploaded_by) REFERENCES users(id), INDEX media_owner(user_id,purpose)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS password_resets (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NOT NULL, token_hash CHAR(64) NOT NULL UNIQUE,
 expires_at DATETIME NOT NULL, used_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id), INDEX reset_user(user_id)
) ENGINE=InnoDB;
