<form method="get" class="panel work-form ess-filter"><input type="hidden" name="page" value="attendance"><label>Overview month<input type="month" name="month" value="<?=h($month)?>" required></label><button class="primary">Apply</button><button type="button" class="wide-button" data-dialog-open="correction-dialog">Request a correction</button></form>
<div class="ess-metrics"><?php foreach(['Recorded work'=>ess_hours(array_sum(array_column($rows,'working_minutes'))),'Late arrivals'=>count(array_filter($rows,fn($r)=>$r['late_minutes']>0)),'Late time'=>ess_hours(array_sum(array_column($rows,'late_minutes'))),'Early departures'=>count(array_filter($rows,fn($r)=>$r['early_minutes']>0)),'Early time'=>ess_hours(array_sum(array_column($rows,'early_minutes'))),'Overtime'=>ess_hours(array_sum(array_column($rows,'overtime_minutes')))] as $label=>$value):?><section class="panel"><small><?=h($label)?></small><h2><?=h($value)?></h2></section><?php endforeach;?></div>
<section class="panel ess-attendance-sheet">
 <div class="ess-section-heading"><div><h2>Attendance sheet · <?=h(date('F Y',strtotime($from)))?></h2><p>Each date is the shift start date. Overnight check-outs can fall on the following day.</p></div><span class="ess-attendance-count"><?=count($rows)?> days</span></div>
 <?php $reviewCount=count(array_filter($rows,fn($r)=>in_array($r['status'],['Review needed','Check-out missing'],true)));if($reviewCount):?><p class="ess-attendance-notice" role="status"><?= $reviewCount ?> <?= $reviewCount===1?'day needs':'days need' ?> attention. Invalid punch durations are excluded from totals; missing check-outs are not estimated. Use Request a correction.</p><?php endif;?>
 <div class="table-scroll ess-attendance-scroll" tabindex="0" role="region" aria-label="Monthly employee attendance"><table data-freeze-first="true"><thead><tr><th scope="col">Shift date</th><th scope="col">Shift / schedule</th><th scope="col">Status</th><th scope="col">Check in</th><th scope="col">Check out</th><th scope="col">Worked</th><th scope="col">Late arrival</th><th scope="col">Early departure</th><th scope="col">Overtime</th><th scope="col">Details</th></tr></thead><tbody>
 <?php foreach($rows as $r):$needsReview=$r['status']==='Review needed';$missing=$r['status']==='Check-out missing';$pending=in_array($r['status'],['Open','Check-out missing'],true);?>
 <tr><th scope="row"><?=h(date('d M Y',strtotime($r['date'])))?><small><?=h(date('l',strtotime($r['date'])))?></small></th>
 <td><?=h($r['shift'])?><?php if($r['scheduled_in']&&$r['scheduled_out']):?><small><?=h(att_time_label($r['scheduled_in']))?> – <?=h(att_time_label($r['scheduled_out']))?><?=substr($r['scheduled_out'],0,10)>$r['date']?' · next day':''?></small><?php endif;?></td>
 <td><span class="ess-attendance-badge <?=($needsReview||$missing)?'needs-review':''?>"><?=h($r['status']==='Open'?'Checked in':$r['status'])?></span></td>
 <td class="ess-punch-time"><?=h(att_time_label($r['check_in'],true,true))?></td><td class="ess-punch-time"><?=h(att_time_label($r['check_out'],true,true))?></td>
 <td><?=h(($needsReview||$pending)?'—':ess_hours($r['working_minutes']))?></td><td><?=h($needsReview?'—':ess_hours($r['late_minutes']))?></td><td><?=h(($needsReview||$pending)?'—':ess_hours($r['early_minutes']))?></td><td><?=h(($needsReview||$pending)?'—':ess_hours($r['overtime_minutes']))?></td>
 <td class="ess-attendance-detail"><?=h($r['note']?:($pending?'Waiting for a check-out.':'—'))?></td></tr>
 <?php endforeach;if(!$rows):?><tr><td colspan="10">No attendance records for this month.</td></tr><?php endif;?></tbody></table></div>
</section>
<?php $requestKind='regularisation';$requestFrom=$from;$requestTo=$to;require __DIR__.'/requests-list.php';$dialogKind='correction';require __DIR__.'/request-dialog.php';?>
