<?php require_once __DIR__.'/attendance-metrics.php';foreach($rows as &$metricRow)$metricRow=array_merge($metricRow,ess_attendance_metrics($metricRow));unset($metricRow);?>
<form method="get" class="panel work-form ess-filter"><input type="hidden" name="page" value="attendance"><label>Overview month<input type="month" name="month" value="<?=h($month)?>" required></label><button class="primary">Apply</button><button type="button" class="wide-button" data-dialog-open="correction-dialog">Request a correction</button></form>
<section class="panel ess-today-summary" data-attendance-today>
 <div class="ess-section-heading"><div><span class="eyebrow">CURRENT SHIFT</span><h2>Today’s time</h2><p data-attendance-live-shift>Loading your shift…</p></div><span class="ess-attendance-badge" data-attendance-live-state>Updating</span></div>
 <div class="ess-time-grid"><?php foreach(['worked'=>['Worked','Time worked, excluding recorded breaks'],'late'=>['Late arrival','Time after the shift started'],'early'=>['Early arrival','Time before the shift started'],'overtime'=>['Net overtime','After-shift time minus late arrival']] as $key=>$item):?><div><span><?=h($item[0])?></span><strong data-attendance-live="<?=h($key)?>">—</strong><small><?=h($item[1])?></small></div><?php endforeach;?></div>
 <p class="ess-hint" data-attendance-live-note>Waiting for the latest punch data.</p>
</section>
<p class="ess-month-caption">Selected month · <?=h(date('F Y',strtotime($from)))?></p>
<div class="ess-metrics"><?php foreach(['Recorded work'=>ess_hours(array_sum(array_column($rows,'working_minutes'))),'Late arrivals'=>count(array_filter($rows,fn($r)=>$r['arrival_late_minutes']>0)),'Late time'=>ess_hours(array_sum(array_column($rows,'arrival_late_minutes'))),'Early arrivals'=>count(array_filter($rows,fn($r)=>$r['arrival_early_minutes']>0)),'Early arrival time'=>ess_hours(array_sum(array_column($rows,'arrival_early_minutes'))),'Net overtime'=>ess_hours(array_sum(array_column($rows,'net_overtime_minutes')))] as $label=>$value):?><section class="panel"><small><?=h($label)?></small><h2><?=h($value)?></h2></section><?php endforeach;?></div>
<section class="panel ess-attendance-sheet">
 <div class="ess-section-heading"><div><h2>Attendance sheet · <?=h(date('F Y',strtotime($from)))?></h2><p>Dates follow the shift start, including overnight shifts. Worked uses saved attendance hours after break deductions.</p></div><span class="ess-attendance-count"><?=count($rows)?> days</span></div>
 <?php $reviewCount=count(array_filter($rows,fn($r)=>in_array($r['status'],['Review needed','Check-out missing'],true)));if($reviewCount):?><p class="ess-attendance-notice" role="status"><?= $reviewCount ?> <?= $reviewCount===1?'day needs':'days need' ?> attention. Invalid punch durations are excluded from totals; missing check-outs are not estimated. Use Request a correction.</p><?php endif;?>
 <p class="ess-time-rule"><strong>Net overtime</strong> = time after shift end − late arrival, minimum zero. Early arrival does not add overtime. Payroll approval remains separate.</p>
 <div class="table-scroll ess-attendance-scroll" tabindex="0" role="region" aria-label="Monthly employee attendance"><table data-freeze-first="true"><thead><tr><th scope="col">Shift date</th><th scope="col">Shift / schedule</th><th scope="col">Status</th><th scope="col">Check in</th><th scope="col">Check out</th><th scope="col">Worked</th><th scope="col">Late arrival</th><th scope="col">Early arrival</th><th scope="col">Net overtime</th><th scope="col">Details</th></tr></thead><tbody>
 <?php foreach($rows as $r):$needsReview=$r['status']==='Review needed';$missing=$r['status']==='Check-out missing';$pending=in_array($r['status'],['Open','Check-out missing'],true);?>
 <tr><th scope="row"><?=h(date('d M Y',strtotime($r['date'])))?><small><?=h(date('l',strtotime($r['date'])))?></small></th>
 <td><?=h($r['shift'])?><?php if($r['scheduled_in']&&$r['scheduled_out']):?><small><?=h(att_time_label($r['scheduled_in']))?> – <?=h(att_time_label($r['scheduled_out']))?><?=substr($r['scheduled_out'],0,10)>$r['date']?' · next day':''?></small><?php endif;?></td>
 <td><span class="ess-attendance-badge <?=($needsReview||$missing)?'needs-review':''?>"><?=h($r['status']==='Open'?'Checked in':$r['status'])?></span></td>
 <td class="ess-punch-time"><?=h(att_time_label($r['check_in'],true,true))?></td><td class="ess-punch-time"><?=h(att_time_label($r['check_out'],true,true))?></td>
 <td><?=h(($needsReview||$pending)?'—':ess_hours($r['working_minutes']))?></td><td><?=h($needsReview?'—':ess_hours($r['arrival_late_minutes']))?></td><td><?=h($needsReview?'—':ess_hours($r['arrival_early_minutes']))?></td><td><?=h(($needsReview||$pending||$r['net_overtime_minutes']===null)?'—':ess_hours($r['net_overtime_minutes']))?></td>
 <td class="ess-attendance-detail"><?=h($r['note']?:($pending?'Waiting for a check-out.':'—'))?><?php if(!$needsReview&&$r['early_minutes']>0):?><small>Left before shift end: <?=h(ess_hours($r['early_minutes']))?></small><?php endif;if($r['after_shift_minutes']!==null&&$r['after_shift_minutes']>0):?><small>After shift: <?=h(ess_hours($r['after_shift_minutes']))?> · Late deducted: <?=h(ess_hours(min($r['after_shift_minutes'],$r['arrival_late_minutes'])))?></small><?php endif;?></td></tr>
 <?php endforeach;if(!$rows):?><tr><td colspan="10">No attendance records for this month.</td></tr><?php endif;?></tbody></table></div>
</section>
<?php $requestKind='regularisation';$requestFrom=$from;$requestTo=$to;require __DIR__.'/requests-list.php';$dialogKind='correction';require __DIR__.'/request-dialog.php';?>
