<?php
require_once __DIR__.'/workflow.php';
require_once dirname(__DIR__).'/attendance/manual.php';
function ess_own_rows(PDO $db,int $owner,string $module):array {$q=$db->prepare('SELECT * FROM hr_records WHERE employee_id=? AND module=? ORDER BY id DESC LIMIT 500');$q->execute([$owner,$module]);$rows=$q->fetchAll(PDO::FETCH_ASSOC);foreach($rows as &$r)$r['values']=json_decode($r['data'],true)?:[];return $rows;}
function ess_hours($minutes):string{return sprintf('%02dh %02dm',intdiv((int)$minutes,60),(int)$minutes%60);}
function ess_events(PDO $db,array $employee):array {$out=[];foreach(chr_rows($db,'company_events') as $r){$v=$r['values'];if($r['status']!=='Active')continue;$allowed=($v['audience']??'')==='Everyone'||(($v['audience']??'')==='Department'&&(int)$v['department_id']===(int)$employee['department_id'])||(($v['audience']??'')==='Selected Employees'&&in_array((int)$employee['user_id'],array_map('intval',$v['employee_ids']??[]),true));if($allowed)$out[]=['title'=>$r['title'],'start'=>$v['start'],'end'=>$v['end'],'description'=>$v['description']??''];}foreach(chr_rows($db,'holidays') as $r)if($r['status']==='Published')$out[]=['title'=>$r['title'],'start'=>$r['values']['date'],'end'=>$r['values']['date'],'description'=>'Holiday'];usort($out,fn($a,$b)=>strcmp($a['start'],$b['start']));return $out;}
function ess_inbox(PDO $db,array $actor):array {
 $items=[];$q=$db->prepare('SELECT * FROM hr_requests WHERE user_id=? ORDER BY updated_at DESC LIMIT 100');$q->execute([$actor['id']]);foreach($q as $r)$items[]=['key'=>'request:'.$r['id'].':'.$r['status'],'title'=>ucfirst($r['kind']).' · '.$r['status'],'text'=>$r['subject'],'at'=>$r['updated_at'],'page'=>['leave'=>'leave_history','regularisation'=>'regularisation','helpdesk'=>'helpdesk'][$r['kind']]];
 foreach(['tasks','reviews'] as $module)foreach(ess_own_rows($db,(int)$actor['id'],$module) as $r){if($module==='reviews'&&$r['status']!=='Published')continue;$items[]=['key'=>'record:'.$r['id'].':'.$r['version'],'title'=>$module==='tasks'?'Task update':'Performance review published','text'=>$r['title'],'at'=>$r['updated_at']??$r['created_at'],'page'=>$module==='tasks'?'tasks':'performance'];}
 foreach($db->query('SELECT * FROM hr_announcements ORDER BY id DESC LIMIT 30') as $r)$items[]=['key'=>'notice:'.$r['id'],'title'=>'Company announcement','text'=>$r['title'],'at'=>$r['created_at'],'page'=>'announcements'];
 if(can($db,$actor,'leave.approve')){foreach($db->query("SELECT * FROM hr_requests WHERE kind='leave' AND status='Pending'") as $r)if(ess_can_review($db,$actor,$r))$items[]=['key'=>'approval:'.$r['id'],'title'=>'Leave approval required','text'=>$r['subject'],'at'=>$r['created_at'],'page'=>'approvals'];}
 require_once dirname(__DIR__).'/payroll/config.php';if(pay_ready($db)){$pq=$db->prepare('SELECT e.id,e.payslip_number,e.published_at,r.month FROM hr_payroll_entries e JOIN hr_payroll_runs r ON r.id=e.run_id WHERE e.employee_id=? AND e.published_at IS NOT NULL ORDER BY e.published_at DESC LIMIT 24');$pq->execute([$actor['id']]);foreach($pq as $p)$items[]=['key'=>'payslip:'.$p['id'],'title'=>'Payslip published','text'=>$p['month'].' · '.$p['payslip_number'],'at'=>$p['published_at'],'page'=>'payroll'];}
 $states=[];foreach(ess_own_rows($db,(int)$actor['id'],'inbox_state') as $r)$states[$r['title']]=$r['status'];foreach($items as &$i)$i['state']=$states[$i['key']]??'Unread';unset($i);usort($items,fn($a,$b)=>strcmp($b['at'],$a['at']));return $items;
}
function ess_post(PDO $db,array $actor,string $page,array $in,array $files=[]):void {
 $action=$in['action']??'';
 if($action==='ess_punch'&&$page==='overview'){ess_web_punch($db,$actor,$in);return;}
 if($action==='ess_inbox'){$valid=array_column(ess_inbox($db,$actor),'key');$key=ftext($in,'key',190,true);$state=$in['state']??'';if(!in_array($key,$valid,true)||!in_array($state,['Read','Unread','Archived'],true))throw new InvalidArgumentException('Notification unavailable.');$db->beginTransaction();try{chr_lock($db);$q=$db->prepare("SELECT id FROM hr_records WHERE module='inbox_state' AND employee_id=? AND title=? FOR UPDATE");$q->execute([$actor['id'],$key]);$id=$q->fetchColumn();if($id)$db->prepare('UPDATE hr_records SET status=?,version=version+1 WHERE id=?')->execute([$state,$id]);else $db->prepare("INSERT INTO hr_records(module,employee_id,title,status,data,created_by) VALUES('inbox_state',?,?,?,'{}',?)")->execute([$actor['id'],$key,$state,$actor['id']]);$db->commit();}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}return;}
 if($action==='ess_profile'){$photo=fimage($files['photo']??[]);$values=[];foreach(['personal_email'=>190,'mobile'=>40,'current_address'=>2000,'permanent_address'=>2000,'emergency_name'=>150,'emergency_phone'=>40,'emergency_relationship'=>80] as $k=>$max)$values[$k]=$k==='personal_email'?femail($in,$k):ftext($in,$k,$max);$db->beginTransaction();try{$set=implode(',',array_map(fn($k)=>$k.'=?',array_keys($values)));$q=$db->prepare("UPDATE employees SET $set,version=version+1 WHERE user_id=? AND deleted_at IS NULL AND version=?");$q->execute([...array_values($values),$actor['id'],(int)($in['version']??0)]);if(!$q->rowCount())throw new InvalidArgumentException('Profile changed. Reload before saving.');save_media($db,$actor,(int)$actor['id'],'profile',$photo);faudit($db,$actor,'employee.self_profile',(int)$actor['id']);$db->commit();}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}return;}
 if($action==='ess_decision'&&$page==='approvals'){chr_review_leave($db,$actor,(int)($in['id']??0),(string)($in['status']??''),ftext($in,'reason',3000));return;}
 throw new InvalidArgumentException('Action not available.');
}

function ess_web_punch(PDO $db,array $actor,array $in):void {
 if(!att_ready($db)||empty(att_config($db)['web_punch_enabled']))throw new InvalidArgumentException('Web attendance is disabled.');
 $action=$in['punch_action']??'';if(!in_array($action,['Check In','Check Out'],true))throw new InvalidArgumentException('Choose a punch action.');$nonce=(string)($in['request_key']??'');if(!preg_match('/^[a-f0-9]{64}$/D',$nonce))throw new InvalidArgumentException('Reload the punch form.');$owner=(int)$actor['id'];att_active_employee($db,$owner);$at=date('Y-m-d H:i:s');$key=hash('sha256',$owner.':'.$nonce);
 $db->beginTransaction();try{chr_lock($db);$q=$db->prepare('SELECT id FROM hr_manual_punch_events WHERE request_key=?');$q->execute([$key]);if($q->fetchColumn())throw new InvalidArgumentException('This punch was already saved.');
 $q=$db->prepare('SELECT * FROM hr_attendance WHERE employee_id=? AND check_out IS NULL ORDER BY attendance_date DESC LIMIT 1 FOR UPDATE');$q->execute([$owner]);$open=$q->fetch(PDO::FETCH_ASSOC);
 if($action==='Check In'&&$open)throw new InvalidArgumentException('An open check-in already exists. Check out or request a correction.');if($action==='Check Out'&&(!$open||strtotime($at)-strtotime($open['check_in'])>36*3600))throw new InvalidArgumentException('No current open check-in. Request an attendance correction.');
 $day=$open['attendance_date']??date('Y-m-d');if($action==='Check In'){$q=$db->prepare('SELECT id FROM hr_attendance WHERE employee_id=? AND attendance_date=?');$q->execute([$owner,$day]);if($q->fetchColumn())throw new InvalidArgumentException('Attendance already exists today. Request a correction.');}$note='Employee self-service '.$action;
 chr_save_attendance($db,$actor,['employee_id'=>$owner,'id'=>$open['id']??0,'version'=>$open['version']??0,'attendance_date'=>$day,'check_in'=>$open['check_in']??$at,'check_out'=>$action==='Check Out'?$at:null,'source'=>'Employee Web','notes'=>$note],true);
 $db->prepare('INSERT INTO hr_manual_punch_events(employee_id,attendance_date,action,punched_at,source,actor_id,notes,request_key) VALUES(?,?,?,?,?,?,?,?)')->execute([$owner,$day,$action,$at,'Employee Web',$owner,$note,$key]);$db->commit();
 }catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
}

function ess_balances(PDO $db,int $owner,int $year):array {
 $out=[];foreach(chr_rows($db,'leave_policy') as $p){if($p['status']!=='Published')continue;$type=$p['values']['type'];$allocation=chr_entitlement($db,$owner,$type,$year)??0;$used=chr_used($db,$owner,$type,$year);$out[]=['type'=>$p['title'],'available'=>$allocation-$used];}return $out;
}
