<?php

?>
<?php
try{[$from,$to]=chr_report_range($page,$_GET);$daily=chr_report($pdo,$from,$to,$_GET);$rows=$page==='monthly'?chr_monthly($daily):$daily;}catch(InvalidArgumentException $e){echo '<div class="alert error">'.h($e->getMessage()).'</div>';return;}
$totals=['present'=>0,'absent'=>0,'leave'=>0,'late_count'=>0];foreach($daily as $r)foreach($totals as $k=>$n)$totals[$k]+=$r[$k];?><div class="stats"><?php foreach(['present'=>'Present day equivalents','absent'=>'Absent day equivalents','leave'=>'Approved leave days','late_count'=>'Late arrivals'] as $key=>$label):?><section class="card"><p class="eyebrow"><?=h($label)?></p><h2><?=h($totals[$key])?></h2></section><?php endforeach;?></div>
<?php
if(isset($_GET['edit']))require dirname(__DIR__).'/attendance/attendance-editor.php';
?>
<form method="get" class="card form-grid core-form"><?php chr_hidden('page',$page);if($page==='monthly')field('month','Month',$_GET+['month'=>date('Y-m')],'month',true);elseif($page==='attendance_history'){field('from','From',$_GET+['from'=>date('Y-m-01')],'date',true);field('to','To',$_GET+['to'=>date('Y-m-d')],'date',true);}else field('date','Date',$_GET+['date'=>date('Y-m-d')],'date',true);chr_select('employee_id','Employee',$_GET['employee_id']??'', [''=>'All employees']+$historyEmployeeOptions);chr_select('department_id','Department',$_GET['department_id']??'', [''=>'All departments']+$departmentOptions);chr_select('shift_id','Shift',$_GET['shift_id']??'', [''=>'All shifts']+$shiftOptions);if($page!=='monthly')chr_select('status','Status',$_GET['status']??'',array_combine(['','Present','Late','Absent','Open','Half Day','Half Day Leave','Leave','Holiday','Week Off','Unscheduled','Pending','Not started','Not active','Review needed'],['All statuses','Present','Late','Absent','Open','Half Day','Half Day Leave','Leave','Holiday','Week Off','Unscheduled','Pending','Not started','Not active','Review needed']));field('search','Search name or employee ID',$_GET);?><div class="full"><button class="button primary">Apply filters</button><?php if(can($pdo,$user,'attendance.reports')):?> <button class="button" name="export" value="1">Download CSV</button><?php endif;?></div></form>

<p>Past scheduled days without a punch or approved leave are absent. Today and future days remain pending. Unassigned shifts do not imply absence. Half-day leave and presence are counted separately; open punches need check-out.</p>
<section class="card"><div class="table-scroll attendance-table-scroll" tabindex="0" role="region" aria-label="Attendance report"><table class="directory" data-freeze-first="true"><thead><tr><th>Employee</th><th>ID / department</th><?php if($page==='monthly'):foreach(['Working days','Present','Absent','Leave','Paid leave','Unpaid leave','Holidays','Week offs','Late count','Half days','Worked','Overtime'] as $label):?><th><?=h($label)?></th><?php endforeach;else:foreach(['Date / shift','Check-in','Check-out','Worked','Late','Early','Overtime','Status','Source','Actions'] as $label):?><th><?=h($label)?></th><?php endforeach;endif;?></tr></thead><tbody><?php $number=max(1,(int)($_GET['p']??1));$shown=array_slice($rows,($number-1)*50,50);if(!$shown):?><tr><td colspan="13">No matching attendance.</td></tr><?php endif;foreach($shown as $r):?><tr><td><?=h($r['name'])?></td><td><?=h($r['employee_code']?:'Not assigned')?><small><?=h($r['department'])?></small></td><?php if($page==='monthly'):foreach(['working_days','present','absent','leave','paid_leave','unpaid_leave','holidays','week_offs','late_count','half_days','working_minutes','overtime_minutes'] as $key):?><td><button type="button" class="record-cell" data-open-dialog="month-<?=$r['employee_id']?>" aria-label="View <?=h($r['name'])?> daily details"><?=h(str_ends_with($key,'minutes')?chr_hours($r[$key]):$r[$key])?></button></td><?php endforeach;else:?><td><?=h($r['date'])?><small><?=h($r['shift'])?></small></td><td><?=h($r['check_in']?:'—')?></td><td><?=h($r['check_out']?:'—')?></td><?php foreach(['working_minutes','late_minutes','early_minutes','overtime_minutes'] as $key):?><td><?=h(chr_hours($r[$key]))?></td><?php endforeach;?><td><?php fbadge($r['status'],!in_array($r['status'],['Absent','Open','Review needed'],true));?><small><?=h($r['note'])?></small></td><td><?=h($r['source'])?></td><td><?php if($r['record_id']&&can($pdo,$user,'attendance.manage')):?><a class="button" href="?page=attendance&date=<?=h($r['date'])?>&edit=<?=(int)$r['record_id']?>">Edit / check-out</a><?php endif;?></td><?php endif;?></tr><?php endforeach;?></tbody></table></div><nav class="pagination" aria-label="Report pages"><?php for($i=max(1,$number-2);$i<=min((int)ceil(count($rows)/50),$number+2);$i++):?><a class="button" href="?<?=h(http_build_query(array_merge($_GET,['p'=>$i])))?>"><?=$i?></a><?php endfor;?></nav></section>

<?php if($user['role']==='super_admin'&&att_biometric_enabled($pdo)):?><p><a class="button" href="?page=device_attendance">Existing device punch reports</a> <a class="button" href="?page=raw_logs">Raw biometric logs</a> <a class="button" href="?page=sync">Sync history</a></p><p>Mapped biometric punches are automatically processed into daily attendance. Pending punches retry while the office bridge is running; manual attendance stays protected.</p><?php endif;?>

<?php if($page==='monthly'):foreach($shown as $summary):?><dialog class="attendance-dialog" id="month-<?=$summary['employee_id']?>"><h2><?=h($summary['name'])?> · <?=h($from)?> to <?=h($to)?></h2><p>Daily records behind this monthly summary.</p><div class="table-scroll"><table class="directory"><thead><tr><th>Date</th><th>Status</th><th>Check-in</th><th>Check-out</th><th>Worked</th><th>Overtime</th></tr></thead><tbody><?php foreach($daily as $detail):if($detail['employee_id']!==$summary['employee_id'])continue;?><tr><td><?=h($detail['date'])?></td><td><?=h($detail['status'])?></td><td><?=h($detail['check_in']?:'—')?></td><td><?=h($detail['check_out']?:'—')?></td><td><?=h(chr_hours($detail['working_minutes']))?></td><td><?=h(chr_hours($detail['overtime_minutes']))?></td></tr><?php endforeach;?></tbody></table></div><div class="form-actions"><button class="button" type="button" data-close-dialog>Close</button></div></dialog><?php endforeach;endif;?>
