<?php
$module=$page;$permission=['shifts'=>'shifts.manage','roster'=>'shifts.manage','holidays'=>'holidays.manage','leave_policy'=>'leave.manage','balances'=>'leave.manage'][$module];$editable=can($pdo,$user,$permission);$edit=isset($_GET['edit'])?chr_record($pdo,$module,(int)$_GET['edit']):null;$v=$edit?array_merge($edit['values'],['title'=>$edit['title'],'employee_id'=>$edit['employee_id']]):[];
if($error&&($_POST['action']??'')==='core_config')$v=array_merge($v,$_POST);
if($module==='shifts'):?><p>Configure working hours, overnight shifts and weekly offs. Existing assignments retain their original rules when a shift is edited. Grace periods suppress late/early flags within the tolerance; beyond it, the full duration is shown.</p><a class="button" href="?page=roster">Employee assignments →</a> <a class="button" href="?page=shift_defaults">Department / company defaults →</a><?php endif;
if($module==='shifts'&&$editable):?><section class="card"><h2>Company shift setup</h2><p>Day Shift: 09:00 AM–06:00 PM. Night Shift: 06:00 PM–09:00 AM (Ends next day). Both use a 1h 30m break and Saturday/Sunday off. Existing assignment snapshots remain unchanged; assign updated rules from the intended effective date.</p><form method="post"><?php ftoken();chr_hidden('action','att_company_shifts');?><button class="button">Set up Day &amp; Night shifts</button></form></section><?php endif;
$leaveDialog=in_array($module,['balances','leave_policy'],true);$leaveLabel=$module==='leave_policy'?'leave type':'leave balance';
if($editable):?><?php if($leaveDialog):?><div class="balance-actions"><button type="button" class="button primary" data-open-dialog="leave-balance-dialog">+ Add <?=h($leaveLabel)?></button></div><dialog id="leave-balance-dialog" class="attendance-dialog balance-dialog" aria-labelledby="balance-dialog-title" <?=($edit||($error&&($_POST['action']??'')==='core_config'))?'data-auto-open':''?>><div class="card-heading"><div><h2 id="balance-dialog-title"><?=h(($edit?'Edit ':'Add ').$leaveLabel)?></h2><p class="hint"><?=h($module==='leave_policy'?'Configure allocation, carry-forward and rules for this leave type.':'Set an employee’s allocation for one leave type and year.')?></p></div><button type="button" class="button small" data-close-dialog aria-label="Close form">Close</button></div><?php if($error):?><p role="alert" class="alert error"><?=h($error)?></p><?php endif;?><?php else:?><details class="card core-editor" <?=($edit||$error||($module!=='balances'&&!chr_rows($pdo,$module)))?'open':''?>><summary><?=h($edit?'Edit '.$edit['title']:'Add '.$pages[$page][0])?></summary><?php endif;?><form method="post" class="form-grid core-form"><?php ftoken();chr_hidden('action','core_config');chr_hidden('module',$module);chr_hidden('id',$edit['id']??0);chr_hidden('version',$edit['version']??0);field('title','Name',$v,'text',true);
if(in_array($module,['roster','balances'],true))chr_select('employee_id','Employee',$v['employee_id']??'', [''=>'Select employee']+$employeeOptions);
if($module==='shifts'){
 field('code','Shift code',$v,'text',true,40);att_time_input('start','Start time',$v);att_time_input('end','End time',$v);echo '<p class="hint full">An end time earlier than the start time means an overnight shift: Ends next day.</p>';foreach(['required_hours'=>'Required working hours','half_day_hours'=>'Half-day threshold (hours)','grace'=>'Late grace (minutes)','early_grace'=>'Early exit grace (minutes)','break_minutes'=>'Unpaid break (minutes)'] as $key=>$label){echo '<label>'.h($label).'<input name="'.h($key).'" type="number" min="0" step="0.5" value="'.h($v[$key]??0).'" required></label>';}
 choose('overtime_rule','Overtime starts',$v,['After required hours','After shift end','After both']);echo '<fieldset class="full"><legend>Weekly off days</legend><div class="core-weekdays">';foreach([1=>'Monday',2=>'Tuesday',3=>'Wednesday',4=>'Thursday',5=>'Friday',6=>'Saturday',7=>'Sunday'] as $n=>$label)echo '<label><input type="checkbox" name="week_off[]" value="'.$n.'" '.(in_array($n,array_map('intval',$v['week_off']??[]),true)?'checked':'').'> '.h($label).'</label>';echo '</div></fieldset>';
}elseif($module==='roster'){chr_select('shift_id','Shift',$v['shift_id']??'', [''=>'Select shift']+$shiftOptions);field('from','Effective from',$v,'date',true);field('to','Effective to (optional)',$v,'date');
}elseif($module==='holidays'){field('date','Holiday date',$v,'date',true);choose('holiday_type','Holiday type',$v,['Company Holiday','Public Holiday','Optional Holiday']);field('description','Description',$v,'text',false,2000);
}elseif($module==='leave_policy'){field('type','Leave code',$v,'text',true,40);foreach(['annual_days'=>'Annual allocation (days)','carry_forward'=>'Maximum carry-forward (days)'] as $key=>$label)echo '<label>'.h($label).'<input type="number" name="'.h($key).'" min="0" max="366" step="0.5" value="'.h($v[$key]??0).'" required></label>';chr_checkbox('paid','Paid leave',!empty($v['paid']));chr_checkbox('allow_negative','Allow negative balance',!empty($v['allow_negative']));
}else{field('year','Allocation year',$v+['year'=>date('Y')],'number',true);$code=$v['type']??array_key_first($leaveOptions);chr_select('type','Leave type',$code,$leaveOptions);echo '<label>Allocated days<input type="number" name="allocation" min="0" max="366" step="0.5" value="'.h($v['allocation']??$v['allocation_details'][$code]['allocated']??$v[$code]??0).'" required></label><label>Carry-forward days<input type="number" name="carry" min="0" max="366" step="0.5" value="'.h($v['carry']??$v['allocation_details'][$code]['carry']??0).'" required></label><p class="full">Choose a leave type and enter its allocation. Other types in this employee’s year remain unchanged. Carry-forward is entered explicitly; it is not automatically rolled over.</p>';}
if($module!=='holidays')field('notes','Notes',$v,'text',false,2000);chr_checkbox('active','Active / published',$error?isset($_POST['active']):(!$edit||in_array($edit['status'],['Active','Published'],true)));?><div class="full"><button class="button primary">Save</button> <a class="button" href="?page=<?=h($page)?>">Clear</a></div></form><?php if($leaveDialog):?></dialog><?php else:?></details><?php endif;?><?php endif;
$rows=chr_rows($pdo,$module);$year=(int)($_GET['year']??date('Y'));if(in_array($module,['holidays','balances'],true)):?><?php if($module==='holidays'):?><form method="get" class="toolbar"><?php chr_hidden('page',$page);field('year','Year',['year'=>$year],'number',true);?><button class="button">Filter</button></form><?php endif; $rows=array_values(array_filter($rows,fn($r)=>$module==='holidays'?(int)substr($r['values']['date']??'',0,4)===$year:(int)($r['values']['year']??0)===$year));endif;
?><?php if($module==='balances'):?><details class="card"><summary>Manage individual allocations</summary><?php endif;?><section class="card"><div class="table-scroll"><table class="directory"><thead><tr><th>Name</th><th><?=in_array($module,['roster','balances'],true)?'Employee':'Details'?></th><th>Configuration</th><th>Status</th><?php if($editable):?><th>Actions</th><?php endif;?></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="5">No records yet.</td></tr><?php endif;foreach($rows as $r):$d=$r['values'];?><tr><td><?=h($r['title'])?></td><td><?php if(in_array($module,['roster','balances'],true))echo h($employeeOptions[$r['employee_id']]??'Archived employee');elseif($module==='shifts')echo h(($d['code']??'').' · '.att_shift_label($r));elseif($module==='holidays')echo h($d['date']??'');else echo h($d['type']??'');?></td><td><?php if($module==='shifts')echo h(($d['required_hours']??$d['overtime_after']??0).'h required · '.($d['grace']??0).'m grace · Break '.sprintf('%02dh %02dm',intdiv((int)($d['break_minutes']??0),60),(int)($d['break_minutes']??0)%60));elseif($module==='roster')echo h(($shiftOptions[$d['shift_id']??0]??'Unknown shift').' · '.($d['from']??'').' → '.($d['to']??'Ongoing'));elseif($module==='holidays')echo h(($d['holiday_type']??'Company Holiday').' · '.($d['description']??''));elseif($module==='leave_policy')echo h(($d['annual_days']??0).' days · '.(!empty($d['paid'])?'Paid':'Unpaid').' · carry cap '.($d['carry_forward']??0));else {foreach($leaveOptions as $code=>$label)if(isset($d[$code]))echo '<div>'.h($code.': '.$d[$code].' allocated').'</div>'; }?></td><td><?php fbadge($r['status'],in_array($r['status'],['Active','Published'],true));?></td><?php if($editable):?><td><a class="button" href="?page=<?=h($page)?>&edit=<?=(int)$r['id']?>">Edit</a><?php if(in_array($module,['shifts','holidays'],true)):?><form class="inline-form" method="post" data-confirm="Delete this unreferenced configuration record?"><?php ftoken();chr_hidden('action','core_delete');chr_hidden('module',$module);chr_hidden('id',$r['id']);?><button class="button">Delete</button></form><?php endif;?></td><?php endif;?></tr><?php endforeach;?></tbody></table></div></section>
<?php if($module==='balances'):?></details><?php endif;?>
<?php if($module==='holidays'):?><p>Published company and public holidays are excluded from new leave requests and absence calculations. Optional holidays remain working days until leave is approved.</p><?php endif;
if($module==='balances')require __DIR__.'/balances-view.php';
