<?php
require_once dirname(__DIR__).'/foundation/core.php';
function chr_ready(PDO $db):bool{try{return (bool)$db->query("SELECT name FROM hr_migrations WHERE name='005-core-hr'")->fetchColumn();}catch(Throwable $e){return false;}}
function chr_install(PDO $db):void{
 if(!foundation_ready($db))throw new InvalidArgumentException('Install Phase 1 first.');
 if(!$db->query("SELECT GET_LOCK('peopleflow_core_hr',10)")->fetchColumn())throw new RuntimeException('Installation in progress.');
 try{if(chr_ready($db))return;foreach(explode(';',file_get_contents(dirname(__DIR__,2).'/database/005-core-hr.sql')) as $sql)if(trim($sql)!=='')$db->exec($sql);
 foreach(['hr_attendance'=>'id,employee_id,attendance_date,check_in,check_out,shift_id,shift_snapshot,working_minutes,late_minutes,early_minutes,overtime_minutes,status,source,notes,version,updated_by,created_at,updated_at','hr_leave_details'=>'request_id,type_record_id,day_part,days,policy_snapshot,attachment_record_id','hr_leave_days'=>'request_id,leave_date,units,day_part'] as $table=>$columns)$db->query('SELECT '.$columns.' FROM '.$table.' LIMIT 0');
 $db->beginTransaction();foreach(['attendance'=>['view','manage','reports'],'leave'=>['view','create','approve','manage'],'holidays'=>['view','manage'],'shifts'=>['view','manage']] as $module=>$actions)foreach($actions as $action)$db->prepare('INSERT IGNORE INTO permissions(code,label) VALUES(?,?)')->execute([$module.'.'.$action,ucfirst($action).' '.$module]);$db->exec("INSERT INTO hr_migrations(name) VALUES('005-core-hr')");$db->commit();}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}finally{$db->query("SELECT RELEASE_LOCK('peopleflow_core_hr')");}
}
function chr_rows(PDO $db,string $module):array{$q=$db->prepare('SELECT * FROM hr_records WHERE module=? ORDER BY id DESC');$q->execute([$module]);$rows=$q->fetchAll(PDO::FETCH_ASSOC);foreach($rows as &$r)$r['values']=json_decode($r['data'],true)?:[];return $rows;}
function chr_record(PDO $db,string $module,int $id):?array{$q=$db->prepare('SELECT * FROM hr_records WHERE module=? AND id=?');$q->execute([$module,$id]);$r=$q->fetch(PDO::FETCH_ASSOC);if(!$r)return null;$r['values']=json_decode($r['data'],true)?:[];return $r;}
function chr_date(string $s):string{$d=fdate(['date'=>$s],'date');if(!$d)throw new InvalidArgumentException('Date is required.');return $d;}
function chr_number(array $in,string $key,float $max=1440):float{$s=$in[$key]??0;if(!is_numeric($s)||!is_finite((float)$s)||(float)$s<0||(float)$s>$max)throw new InvalidArgumentException('Check '.str_replace('_',' ',$key).'.');return (float)$s;}
function chr_time(array $in,string $key):string{$s=ftext($in,$key,5,true);if(!preg_match('/^(?:[01]\d|2[0-3]):[0-5]\d$/',$s))throw new InvalidArgumentException('Enter a valid time.');return $s;}
function chr_lock(PDO $db):void{$db->query("SELECT id FROM users WHERE role='super_admin' ORDER BY id LIMIT 1 FOR UPDATE")->fetchColumn();}
function chr_employee(PDO $db,int $id):array{$e=foundation_employee($db,$id);if(!$e)throw new InvalidArgumentException('Choose an existing employee.');return $e;}
function chr_shift_bounds(string $day,array $s):array{$start=new DateTimeImmutable($day.' '.$s['start']);$end=new DateTimeImmutable($day.' '.$s['end']);if($end<=$start)$end=$end->modify('+1 day');return [$start,$end];}
function chr_assignment(PDO $db,int $employee,string $day):?array{
 $employeeRow=chr_employee($db,$employee);return att_resolve(att_resolution_context($db),$employeeRow,$day);
}
function chr_holiday(PDO $db,string $day):?array{foreach(chr_rows($db,'holidays') as $r)if($r['status']==='Published'&&($r['values']['date']??'')===$day&&($r['values']['holiday_type']??'Company Holiday')!=='Optional Holiday')return $r;return null;}
function chr_weekoff(?array $shift,string $day):bool{return $shift&&in_array((int)date('N',strtotime($day)),array_map('intval',(array)($shift['values']['week_off']??[])),true);}
function chr_calculate(string $day,string $in,?string $out,?array $shift):array{
 $a=new DateTimeImmutable($in);$b=$out?new DateTimeImmutable($out):null;if($a->format('Y-m-d')!==$day)throw new InvalidArgumentException('Check-in must be on the attendance date.');if($b&&($b<=$a||$b->getTimestamp()-$a->getTimestamp()>36*3600))throw new InvalidArgumentException('Check-out must follow check-in, within 36 hours.');
 $result=['working_minutes'=>0,'late_minutes'=>0,'early_minutes'=>0,'overtime_minutes'=>0,'status'=>$b?'Present':'Open'];
 if($b)$result['working_minutes']=max(0,(int)floor(($b->getTimestamp()-$a->getTimestamp())/60)-(int)($shift['break_minutes']??0));
 if(!$shift)return $result;[$start,$end]=chr_shift_bounds($day,$shift);$late=max(0,(int)floor(($a->getTimestamp()-$start->getTimestamp())/60));$result['late_minutes']=$late>(int)($shift['grace']??0)?$late:0;
 if($b){$early=max(0,(int)floor(($end->getTimestamp()-$b->getTimestamp())/60));$result['early_minutes']=$early>(int)($shift['early_grace']??0)?$early:0;$after=max(0,(int)floor(($b->getTimestamp()-$end->getTimestamp())/60));$required=(int)round((float)($shift['required_hours']??$shift['overtime_after']??0)*60);$extra=$required>0?max(0,$result['working_minutes']-$required):0;$rule=$shift['overtime_rule']??'After required hours';$result['overtime_minutes']=$rule==='After shift end'?$after:($rule==='After both'?min($after,$extra):$extra);$half=(int)round((float)($shift['half_day_hours']??0)*60);$result['status']=$half>0&&$result['working_minutes']<$half?'Half Day':($result['late_minutes']>0?'Late':'Present');}
 if($b&&isset($shift['policy_id'])){$hours=$result['working_minutes']/60;$result['status']=$hours<max((float)($shift['minimum_hours']??0),(float)($shift['half_day_hours']??0))?'Absent':($hours<(float)$shift['required_hours']?'Half Day':($result['late_minutes']>0?'Late':'Present'));}
 return $result;
}
function chr_save_config(PDO $db,array $actor,string $module,array $in):int{
 $perms=['shifts'=>'shifts.manage','roster'=>'shifts.manage','holidays'=>'holidays.manage','leave_policy'=>'leave.manage','balances'=>'leave.manage'];if(!isset($perms[$module])||!can($db,$actor,$perms[$module]))throw new InvalidArgumentException('You do not have permission to manage this section.');
 $db->beginTransaction();try{chr_lock($db);$id=(int)($in['id']??0);$old=$id?chr_record($db,$module,$id):null;if($id&&(!$old||(int)$old['version']!==(int)($in['version']??0)))throw new InvalidArgumentException('Record changed. Reload before saving.');$title=ftext($in,'title',190,true);$active=!empty($in['active']);$d=$old['values']??[];$owner=null;
 if($module==='shifts'){
 $d['code']=strtoupper(ftext($in,'code',40,true));foreach(chr_rows($db,$module) as $r)if((int)$r['id']!==$id&&strcasecmp($r['values']['code']??'',$d['code'])===0)throw new InvalidArgumentException('Shift code already exists.');$d['start']=chr_time($in,'start');$d['end']=chr_time($in,'end');if($d['start']===$d['end'])throw new InvalidArgumentException('Start and end cannot be identical.');foreach(['grace','early_grace','break_minutes'] as $k)$d[$k]=chr_number($in,$k);foreach(['required_hours','half_day_hours'] as $k)$d[$k]=chr_number($in,$k,24);if($d['required_hours']<=0||$d['half_day_hours']>$d['required_hours'])throw new InvalidArgumentException('Required hours must be positive and half-day threshold cannot exceed them.');[$a,$b]=chr_shift_bounds('2026-01-01',$d);if($d['break_minutes']>=($b->getTimestamp()-$a->getTimestamp())/60)throw new InvalidArgumentException('Break must be shorter than the shift.');$d['overtime_rule']=$in['overtime_rule']??'';if(!in_array($d['overtime_rule'],['After shift end','After required hours','After both'],true))throw new InvalidArgumentException('Select an overtime rule.');$d['overtime_after']=$d['required_hours'];$d['week_off']=array_values(array_unique(array_map('intval',(array)($in['week_off']??[]))));foreach($d['week_off'] as $n)if($n<1||$n>7)throw new InvalidArgumentException('Invalid week-off day.');$d['notes']=ftext($in,'notes',2000);
 }elseif($module==='roster'){
 $owner=(int)($in['employee_id']??0);chr_employee($db,$owner);$d['notes']=ftext($in,'notes',2000);$d['from']=chr_date((string)($in['from']??''));$d['to']=fdate($in,'to');if($d['to']&&$d['to']<$d['from'])throw new InvalidArgumentException('End date cannot precede start date.');$d['shift_id']=(int)($in['shift_id']??0);$shift=chr_record($db,'shifts',$d['shift_id']);if(!$shift||($shift['status']!=='Active'&&(!$old||(int)($old['values']['shift_id']??0)!==$d['shift_id'])))throw new InvalidArgumentException('Choose an active shift.');
 if($active)foreach(chr_rows($db,'roster') as $r){$v=$r['values'];if((int)$r['id']!==$id&&(int)$r['employee_id']===$owner&&$r['status']==='Active'&&($v['from']??'9999')<=($d['to']?:'9999-12-31')&&(($v['to']??null)?:'9999-12-31')>=$d['from'])throw new InvalidArgumentException('This assignment overlaps an existing assignment. End the old assignment before adding another.');}
 if($old&&($old['values']['from']??'9999')<=date('Y-m-d')&&((int)$old['employee_id']!==$owner||(int)$old['values']['shift_id']!==$d['shift_id']||$old['values']['from']!==$d['from']||!$active))throw new InvalidArgumentException('Preserve started assignments. Set their end date and create a new assignment.');
 if($old&&($old['values']['from']??'9999')<=date('Y-m-d')&&$d['to']&&$d['to']<date('Y-m-d')&&$d['to']!==($old['values']['to']??null))throw new InvalidArgumentException('An assignment end date cannot remove historical days. Use today or a later date.');
 $d['shift_snapshot']=$old&&isset($old['values']['shift_snapshot'])?$old['values']['shift_snapshot']:$shift['values'];if($old&&$old['values']['from']>date('Y-m-d'))$d['shift_snapshot']=$shift['values'];
 }elseif($module==='holidays'){
 $d['date']=chr_date((string)($in['date']??''));$d['description']=ftext($in,'description',2000);$d['holiday_type']=$in['holiday_type']??'';if(!in_array($d['holiday_type'],['Public Holiday','Company Holiday','Optional Holiday'],true))throw new InvalidArgumentException('Choose a holiday type.');if($active)foreach(chr_rows($db,'holidays') as $r)if((int)$r['id']!==$id&&$r['status']==='Published'&&($r['values']['date']??'')===$d['date'])throw new InvalidArgumentException('An active holiday already exists on this date.');
 }elseif($module==='leave_policy'){
 $code=strtoupper(ftext($in,'type',40,true));if(!preg_match('/^[A-Z][A-Z0-9_-]{0,39}$/',$code))throw new InvalidArgumentException('Use a short alphanumeric leave code.');if($old&&($old['values']['type']??'')!==$code){$q=$db->prepare("SELECT id FROM hr_requests WHERE kind='leave' AND category=? LIMIT 1");$q->execute([$old['values']['type']??'']);if($q->fetchColumn())throw new InvalidArgumentException('Leave codes with requests cannot be renamed.');foreach(chr_rows($db,'balances') as $balance)if(array_key_exists($old['values']['type']??'',$balance['values']))throw new InvalidArgumentException('Leave codes with allocations cannot be renamed.');}foreach(chr_rows($db,'leave_policy') as $r)if((int)$r['id']!==$id&&($r['values']['type']??'')===$code)throw new InvalidArgumentException('This leave code already exists. Edit its existing record.');$d['type']=$code;$d['paid']=!empty($in['paid']);$d['annual_days']=chr_number($in,'annual_days',366);$d['carry_forward']=chr_number($in,'carry_forward',366);$d['allow_negative']=!empty($in['allow_negative']);$d['notes']=ftext($in,'notes',2000);
 }else{
 $owner=(int)($in['employee_id']??0);chr_employee($db,$owner);if($old&&(int)$old['employee_id']!==$owner)throw new InvalidArgumentException('The entitlement employee cannot be changed.');$year=(int)chr_number($in,'year',2200);if($year<2000)throw new InvalidArgumentException('Enter a year from 2000 to 2200.');if($old&&(int)($old['values']['year']??0)!==$year)throw new InvalidArgumentException('The entitlement year cannot be changed.');$type=ftext($in,'type',40,true);$policy=chr_policy($db,$type);if(!$policy)throw new InvalidArgumentException('Choose a leave type.');$allocation=chr_number($in,'allocation',366);$carry=chr_number($in,'carry',366);if($carry>(float)($policy['values']['carry_forward']??0))throw new InvalidArgumentException('Carry-forward exceeds the configured cap.');if($active&&!($policy['values']['allow_negative']??false)&&$allocation+$carry<chr_used($db,$owner,$type,$year))throw new InvalidArgumentException('Allocation cannot be lower than already approved usage.');$d['year']=$year;$d[$type]=$allocation+$carry;$d['allocation_details'][$type]=['allocated'=>$allocation,'carry'=>$carry];$d['notes']=ftext($in,'notes',2000);foreach(chr_rows($db,'balances') as $r)if((int)$r['id']!==$id&&(int)$r['employee_id']===$owner&&(int)($r['values']['year']??0)===$year&&$r['status']==='Active')throw new InvalidArgumentException('An entitlement record already exists for this employee and year. Edit it to add or change a type.');
 }
 $status=$active?(in_array($module,['holidays','leave_policy'],true)?'Published':'Active'):($module==='roster'?'Cancelled':(in_array($module,['holidays','leave_policy'],true)?'Draft':'Inactive'));
 if($old&&$module==='shifts')foreach(chr_rows($db,'roster') as $assignment){$values=$assignment['values'];if((int)($values['shift_id']??0)===$id&&!isset($values['shift_snapshot'])){$values['shift_snapshot']=$old['values'];$db->prepare('UPDATE hr_records SET data=?,version=version+1 WHERE id=?')->execute([json_encode($values),$assignment['id']]);}}
 if($old)$db->prepare('UPDATE hr_records SET title=?,status=?,employee_id=?,data=?,version=version+1 WHERE id=?')->execute([$title,$status,$owner,json_encode($d),$id]);else{$db->prepare('INSERT INTO hr_records(module,employee_id,title,status,data,created_by) VALUES(?,?,?,?,?,?)')->execute([$module,$owner,$title,$status,json_encode($d),$actor['id']]);$id=(int)$db->lastInsertId();}faudit($db,$actor,'core.'.$module.'.saved',$id);$db->commit();return $id;
 }catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
}
function chr_delete_config(PDO $db,array $actor,string $module,int $id):void{
 $p=['shifts'=>'shifts.manage','holidays'=>'holidays.manage'];if(!isset($p[$module])||!can($db,$actor,$p[$module]))throw new InvalidArgumentException('Delete is not permitted.');$db->beginTransaction();try{chr_lock($db);$r=chr_record($db,$module,$id);if(!$r)throw new InvalidArgumentException('Record not found.');if($module==='shifts')foreach(array_merge(chr_rows($db,'roster'),chr_rows($db,'shift_defaults'),chr_rows($db,'time_policies')) as $a)if((int)($a['values']['shift_id']??0)===$id)throw new InvalidArgumentException('This shift has assignment history. Deactivate it instead.');if($module==='holidays'&&($r['values']['date']??'')<=date('Y-m-d'))throw new InvalidArgumentException('Preserve past holidays; deactivate only if correcting an error.');$db->prepare('DELETE FROM hr_records WHERE id=? AND module=?')->execute([$id,$module]);faudit($db,$actor,'core.'.$module.'.deleted',$id);$db->commit();}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}}
require_once __DIR__.'/leave.php';
require_once __DIR__.'/attendance.php';

require_once dirname(__DIR__).'/attendance/settings.php';
require_once dirname(__DIR__).'/attendance/shifts.php';
