<?php
if(!chr_ready($pdo)):?><section class="card"><h2>Enable Core HR</h2><p>Add attendance and leave accounting to your existing employee records. No employee accounts, passwords or existing records are replaced.</p><?php if($user['role']==='super_admin'):?><form method="post"><?php ftoken();?><input type="hidden" name="action" value="core_install"><button class="button primary">Enable Core HR</button></form><?php else:?><p>Ask your Super Admin to enable this module.</p><?php endif;?></section><?php return;endif;
function chr_select(string $key,string $label,$selected,array $options):void {echo '<label>'.h($label).'<select name="'.h($key).'">';foreach($options as $value=>$text)echo '<option value="'.h((string)$value).'" '.((string)$value===(string)$selected?'selected':'').'>'.h($text).'</option>';echo '</select></label>';}
function chr_hidden(string $key,$value):void {echo '<input type="hidden" name="'.h($key).'" value="'.h((string)$value).'">';}
function chr_checkbox(string $key,string $label,bool $checked):void {echo '<label class="check"><input type="checkbox" name="'.h($key).'" value="1" '.($checked?'checked':'').'> '.h($label).'</label>';}
function chr_hours($minutes):string{return sprintf('%dh %02dm',intdiv((int)$minutes,60),(int)$minutes%60);}
$employeeOptions=[];foreach($pdo->query('SELECT e.user_id,u.name,e.employee_code FROM employees e JOIN users u ON u.id=e.user_id WHERE e.deleted_at IS NULL ORDER BY u.name') as $e)$employeeOptions[$e['user_id']]=$e['name'].($e['employee_code']?' · '.$e['employee_code']:'');
$historyEmployeeOptions=[];foreach($pdo->query('SELECT e.user_id,u.name,e.employee_code,e.deleted_at FROM employees e JOIN users u ON u.id=e.user_id ORDER BY u.name') as $e)$historyEmployeeOptions[$e['user_id']]=$e['name'].($e['employee_code']?' · '.$e['employee_code']:'').($e['deleted_at']?' (archived)':'');
$shiftOptions=[];foreach(chr_rows($pdo,'shifts') as $s)$shiftOptions[$s['id']]=$s['title'].($s['status']!=='Active'?' (inactive)':'');
$departmentOptions=[];foreach($pdo->query('SELECT id,name FROM departments ORDER BY name') as $d)$departmentOptions[$d['id']]=$d['name'];
$leaveOptions=[];foreach(chr_rows($pdo,'leave_policy') as $l)$leaveOptions[$l['values']['type']??'']=$l['title'].' · '.($l['values']['type']??'');
$group=in_array($page,['leaves','leave_history','leave_policy','balances'],true)?['leaves','leave_policy','balances','leave_history']:['attendance','attendance_history','monthly','holidays','roster'];
if($page!=='shifts'):?><nav class="tabs" aria-label="Core HR sections"><?php foreach($group as $key)if(can($pdo,$user,$pages[$key][1])):?><a href="?page=<?=h($key)?>" <?=$key===$page?'aria-current="page" class="active"':''?>><?=h($pages[$key][0])?></a><?php endif;?></nav><?php endif;
if(in_array($page,['shifts','roster','holidays','leave_policy','balances'],true))require __DIR__.'/configuration-view.php';elseif(in_array($page,['attendance','attendance_history','monthly'],true))require __DIR__.'/attendance-view.php';else require __DIR__.'/leave-view.php';
