<?php
// Field: label, type, required, options. Registry is server-owned, never supplied by a client.
function suite_definitions(): array {
 $text=fn($label,$required=false)=>[$label,'text',$required];
 $date=fn($label,$required=false)=>[$label,'date',$required];
 $number=fn($label,$required=false)=>[$label,'number',$required];
 return [
 'employment'=>['Employee profiles','People','own',true,['Active','Probation','Notice period','Exited'],[
  'employee_code'=>$text('Employee ID'),'department'=>$text('Department'),'designation'=>$text('Designation',true),'manager'=>$text('Reporting manager'),'joining_date'=>$date('Joining date'),'phone'=>$text('Phone'),'birth_date'=>$date('Date of birth'),'location'=>$text('Location'),'emergency_contact'=>$text('Emergency contact'),'blood_group'=>$text('Blood group'),'source_status'=>$text('ID card preparation status'),'bank_name'=>$text('Bank name'),'bank_account'=>$text('Bank account'),'ifsc'=>$text('IFSC')]],
 'devices'=>['Biometric devices','Attendance','admin',false,['Enabled','Disabled'],['device_code'=>$text('Unique device code',true),'model'=>$text('eSSL model'),'location'=>$text('Location'),'host'=>$text('LAN IP / hostname'),'notes'=>['Connection notes','textarea',false]]],
 'mapping'=>['Employee mapping','Attendance','admin',true,['Active','Inactive'],['device_code'=>$text('Device code',true),'biometric_id'=>$text('Biometric employee ID',true)]],
 'shifts'=>['Shifts & rules','Attendance','company',false,['Active','Inactive'],['start'=>['Start time','time',true],'end'=>['End time','time',true],'grace'=>$number('Late grace (minutes)',true),'early_grace'=>$number('Early exit grace (minutes)',true),'break_minutes'=>$number('Unpaid break (minutes)',true),'overtime_after'=>$number('Overtime after (hours)',true),'notes'=>['Policy notes','textarea',false]]],
 'roster'=>['Shift assignments','Attendance','own',true,['Active','Cancelled'],['shift_id'=>$number('Shift record ID',true),'from'=>$date('Effective from',true),'to'=>$date('Effective to',true)]],
 'holidays'=>['Holiday calendar','Leave','company',false,['Published','Draft'],['date'=>$date('Holiday date',true),'location'=>$text('Location'),'description'=>['Description','textarea',false]]],
 'balances'=>['Leave entitlements','Leave','own',true,['Active','Inactive'],['year'=>$number('Year',true),'CL'=>$number('CL entitlement',true),'SL'=>$number('SL entitlement',true),'PL'=>$number('PL entitlement',true),'notes'=>['Policy / adjustments','textarea',false]]],
 'leave_policy'=>['Leave configuration','Leave','company',false,['Published','Draft'],['type'=>['Leave type','select',true,['CL','SL','PL','LWP']],'annual_days'=>$number('Annual days',true),'carry_forward'=>$number('Carry-forward cap'),'notes'=>['Eligibility and rules','textarea',true]]],
 'restricted'=>['Restricted periods','Leave','company',false,['Active','Inactive'],['from'=>$date('From',true),'to'=>$date('To',true),'reason'=>['Reason','textarea',true]]],
 'salary'=>['Salary structures','Payroll','admin',true,['Active','Draft','Archived'],['basic'=>$number('Monthly basic ₹',true),'hra'=>$number('Monthly HRA ₹',true),'other'=>$number('Other monthly earnings ₹',true),'deductions'=>$number('Fixed monthly deductions ₹',true),'effective'=>$date('Effective from',true),'notes'=>['Components / agreed terms','textarea',false]]],
 'contracts'=>['Employment contracts','Payroll','own',true,['Draft','Active','Expired','Terminated'],['type'=>['Contract type','select',true,['Permanent','Fixed term','Probation','Internship','Consultant']],'from'=>$date('Effective from',true),'to'=>$date('End / renewal date'),'ctc'=>$number('Annual CTC ₹',true),'terms'=>['Contract terms','textarea',false]]],
 'advances'=>['Salary advances','Payroll','own',true,['Pending','Approved','Rejected','Repaid'],['amount'=>$number('Advance amount ₹',true),'months'=>$number('Repayment months',true),'balance'=>$number('Outstanding ₹',true),'reason'=>['Reason','textarea',true]]],
 'components'=>['Allowances & deductions','Payroll','admin',false,['Active','Inactive'],['type'=>['Type','select',true,['Earning','Deduction']],'amount'=>$number('Amount ₹',true),'frequency'=>['Frequency','select',true,['Monthly','One-time']],'notes'=>['Eligibility / calculation notes','textarea',true]]],
 'payroll'=>['Payroll & payslips','Payroll','own',true,['Draft','Approved','Published'],['month'=>['Payroll month','month',true],'basic'=>$number('Basic ₹',true),'hra'=>$number('HRA ₹',true),'other'=>$number('Other earnings ₹',true),'overtime'=>$number('Overtime payment ₹',true),'incentive'=>$number('Incentives ₹',true),'deductions'=>$number('Statutory / other deductions ₹',true),'lwp'=>$number('Attendance / LWP deductions ₹',true),'advance'=>$number('Advance recovery ₹',true),'notes'=>['Calculation and approval notes','textarea',true]]],
 'jobs'=>['Job openings','Recruitment','admin',false,['Draft','Open','Closed'],['department'=>$text('Department',true),'location'=>$text('Location',true),'openings'=>$number('Vacancies',true),'description'=>['Job description','textarea',true]]],
 'recruitment'=>['Candidate tracker','Recruitment','admin',false,['Applied','Screening','Interview','Offer','Hired','Rejected'],['email'=>['Candidate email','email',true],'phone'=>$text('Phone'),'job_id'=>$number('Job record ID',true),'source'=>$text('Source'),'notes'=>['Recruiter notes','textarea',false]]],
 'interviews'=>['Interviews','Recruitment','admin',false,['Scheduled','Completed','Cancelled'],['candidate_id'=>$number('Candidate record ID',true),'when'=>['Interview time','datetime-local',true],'interviewer'=>$text('Interviewer',true),'meeting'=>$text('Meeting location / link'),'feedback'=>['Feedback','textarea',false]]],
 'offers'=>['Offer checklist','Recruitment','admin',false,['Draft','Sent','Accepted','Declined'],['candidate_id'=>$number('Candidate record ID',true),'joining_date'=>$date('Proposed joining date'),'ctc'=>$number('Annual CTC ₹',true),'checklist'=>['Checks / offer details','textarea',true]]],
 'onboarding'=>['Onboarding tasks','Onboarding','own',true,['To do','In progress','Completed'],['due'=>$date('Due date',true),'owner'=>$text('Task owner'),'instructions'=>['Instructions','textarea',true]]],
 'exit_tasks'=>['Exit checklist','Offboarding','own',true,['To do','In progress','Completed'],['due'=>$date('Due date',true),'owner'=>$text('Clearance owner',true),'instructions'=>['Clearance / settlement details','textarea',true]]],
 'performance'=>['Goals & KPIs','Performance & PMS','own',true,['Not started','On track','At risk','Completed'],['due'=>$date('Target date',true),'target'=>$number('Target',true),'actual'=>$number('Actual',true),'unit'=>$text('Unit',true),'notes'=>['Progress notes','textarea',false]]],
 'reviews'=>['Performance reviews','Performance & PMS','own',true,['Draft','Published'],['cycle'=>$text('Review cycle',true),'reviewer'=>$text('Reviewer',true),'rating'=>['Rating','select',true,['1','2','3','4','5']],'feedback'=>['Feedback and next steps','textarea',true]]],
 'pip'=>['Improvement plans','Performance & PMS','own',true,['Active','Completed','Closed'],['from'=>$date('Start date',true),'to'=>$date('Review date',true),'objectives'=>['Objectives and support','textarea',true]]],
 'assets'=>['Assets & IT','Assets & IT','own',true,['Assigned','Returned','Lost','Repair'],['asset_tag'=>$text('Asset tag',true),'serial'=>$text('Serial number'),'issued'=>$date('Issue date',true),'return_date'=>$date('Return date'),'notes'=>['Condition / accessories','textarea',false]]],
 'access'=>['Access & licenses','Assets & IT','own',true,['Requested','Granted','Revoked'],['system'=>$text('System / software',true),'expires'=>$date('License expiry'),'notes'=>['Access scope (no passwords)','textarea',true]]],
 'policies'=>['Policies & handbook','Policies','company',false,['Draft','Published','Archived'],['effective'=>$date('Effective date',true),'version'=>$text('Policy version',true),'body'=>['Policy text','textarea',true]]],
 'tasks'=>['Tasks','Tasks','own',true,['To do','In progress','Completed'],['due'=>$date('Due date',true),'priority'=>['Priority','select',true,['Low','Normal','High']],'instructions'=>['Task details','textarea',true]]],
 'documents'=>['Document register','Documents','own',true,['Requested','Received','Verified','Expired'],['type'=>$text('Document type',true),'expires'=>$date('Expiry date'),'notes'=>['Document notes','textarea',false]]],
 'expenses'=>['Expense claims','Expenses','own',true,['Pending','Approved','Rejected','Paid'],['date'=>$date('Expense date',true),'amount'=>$number('Amount ₹',true),'category'=>$text('Category',true),'notes'=>['Business purpose / receipt reference','textarea',true]]],
 'settings'=>['Company settings','Company settings','admin',false,['Active','Inactive'],['legal_name'=>$text('Legal name',true),'address'=>['Office address','textarea',true],'timezone'=>$text('Timezone (IANA)',true),'contact'=>['HR email','email',true]]],
 'departments'=>['Departments','Company settings','company',false,['Active','Inactive'],['head'=>$text('Department head'),'location'=>$text('Location')]],
 'designations'=>['Designations','Company settings','company',false,['Active','Inactive'],['department'=>$text('Department',true),'grade'=>$text('Grade')]]
 ];
}
