<?php if(!$admin&&$coreReady&&!$passwordSetup&&in_array($page,['profile','my_shift','documents','security'],true)):$owner=(int)$user['id'];$employee=foundation_employee($pdo,$owner);$today=date('Y-m-d');if($employee)require __DIR__.'/ess/profile-view.php';else echo '<section class="panel">Your employee profile is not linked. Contact HR.</section>'; elseif(!$admin&&$coreReady&&in_array($page,['overview','profile','my_shift','attendance','attendance_sheet','monthly','regularisation','leaves','balances','leave_history','inbox','notifications','approvals','my_salary'],true)):require __DIR__.'/ess/view.php'; elseif(isset($suite[$page])): if($page==='payroll')echo '<p><a class="button" href="payroll-slip.php">My published payslips</a></p>';suite_render($pdo,$user,$page,$suite[$page],$suiteReady);
elseif(in_array($page,['attendance','monthly','device_attendance','device_monthly','raw_logs','sync','reports'],true)): require __DIR__.'/suite-reports.php';
elseif($page==='overview'):
 $total=$admin?(int)$pdo->query("SELECT COUNT(*) FROM users WHERE role='employee' AND active=1")->fetchColumn():null;
 $pending=0; $approved=0;
 $punchCount=0;$publishedCount=0;
 if($suiteReady){$publishedCount=count(suite_rows($pdo,'payroll',$user,$suite['payroll']));if($admin)$punchCount=(int)$pdo->query("SELECT COUNT(*) FROM hr_punches WHERE punched_at>=CURRENT_DATE() AND punched_at<CURRENT_DATE()+INTERVAL 1 DAY")->fetchColumn();}
 if($ready){$q=$pdo->prepare('SELECT status,COUNT(*) n FROM hr_requests'.($admin?'':' WHERE user_id=?').' GROUP BY status');$q->execute($admin?[]:[$user['id']]);foreach($q as $r){if($r['status']==='Pending')$pending=$r['n'];if($r['status']==='Approved')$approved=$r['n'];}}
 ?><div class="stats"><section class="stat lavender"><div><?= $admin?'Active employees':'My requests' ?></div><strong><?= $admin?$total:($ready?$pending:'—') ?></strong><small><?= $admin?'Employee accounts':'Pending review' ?></small></section><section class="stat mint"><div><?= $admin?'Pending requests':'Approved requests' ?></div><strong><?= $ready?($admin?$pending:$approved):'—' ?></strong><small>Leave, attendance and helpdesk</small></section><section class="stat peach"><div><?= $admin?'Punch events today':'My attendance' ?></div><strong><?= $admin&&$suiteReady?$punchCount:'—' ?></strong><small><a href="?page=attendance">View attendance records</a></small></section><section class="stat blue"><div><?= $admin?'Payroll':'My payslip' ?></div><strong><?= $suiteReady?$publishedCount:0 ?></strong><small><a href="?page=payroll">View payroll records</a></small></section></div><section class="panel"><h2>Hello, <?=h($user['name'])?>.</h2><p style="margin:12px 0">Choose a section to <?= $admin?'manage employee accounts, review requests or publish company notices.':'submit leave, request an attendance correction or contact your team.' ?></p><div class="quick-links"><a class="primary" href="?page=leaves"><?= $admin?'Review leave':'Apply for leave' ?> →</a><a class="wide-button" href="?page=announcements">Company notices →</a><a class="wide-button" href="?page=helpdesk">Helpdesk →</a></div></section>
<?php require __DIR__.'/suite-dashboard.php'; ?>
<?php elseif($page==='employees' && $admin): require __DIR__.'/import-view.php'; ?><section class="panel"><h2>Create employee account</h2><form method="post" class="work-form"><?php token(); ?><input type="hidden" name="action" value="create_employee"><label>Full name<input name="name" maxlength="150" required></label><label>Work email<input name="email" type="email" maxlength="190" required></label><label>Initial password<input name="password" type="password" minlength="12" maxlength="72" autocomplete="new-password" required></label><p>New accounts receive Employee access only. Share the initial password privately.</p><button class="primary" <?= !$ready?'disabled':'' ?>>Create employee</button></form></section><section class="panel"><h2>Employee directory</h2><div class="table-scroll"><table><thead><tr><th>Name</th><th>Email / username</th><th>Account status</th></tr></thead><tbody><?php foreach($pdo->query("SELECT * FROM users WHERE role='employee' ORDER BY name") as $r): ?><tr><td><?=h($r['name'])?></td><td><?=h($r['email']??'Email not added')?> <br><?=h($r['username']??'')?></td><td><?= $r['active']?'Active':'Inactive' ?></td></tr><?php endforeach ?></tbody></table></div></section>
<?php elseif(in_array($page,['leaves','regularisation','helpdesk'],true)):
 $kind=['leaves'=>'leave','regularisation'=>'regularisation','helpdesk'=>'helpdesk'][$page];
 if(!$admin): ?><?php if($kind==='leave'&&$coreReady):try{$route=ess_route($pdo,(int)$user['id']);?><section class="panel"><strong>Send application to</strong><p><?=h(implode($route['mode']==='any'?' or ':' → ',array_column($route['approvers'],'name')))?></p><p>Pending leave does not reserve balance. The final approver rechecks availability.</p></section><?php }catch(InvalidArgumentException $e){echo '<p class="error">'.h($e->getMessage()).'</p>';}endif;?> <section class="panel"><h2><?= $page==='leaves'?'Apply for leave':($page==='regularisation'?'Request attendance correction':'Submit a request') ?></h2><form class="work-form" method="post" enctype="multipart/form-data"><?php token(); ?><input type="hidden" name="action" value="request"><label>Category<select name="category"><?php foreach(($kind==='leave'?$coreLeaveTypes:($kind==='regularisation'?['Missed punch','Incorrect punch','Shift correction']:['HR','Payroll','IT','Other'])) as $c): ?><option><?=h($c)?></option><?php endforeach ?></select></label><label>Subject<input name="subject" maxlength="180" required></label><?php if($kind!=='helpdesk'): ?><div class="form-columns"><label>From<input type="date" name="start_date" required></label><label>To<input type="date" name="end_date" required></label></div><?php endif ?><?php if($kind==='leave'&&$coreReady):?><label>Day period<select name="day_part"><option>Full Day</option><option>First Half</option><option>Second Half</option></select></label><?php endif;?><?php if($kind==='leave'&&$coreReady):?><label>Attachment<input type="file" name="attachment" accept=".pdf,.jpg,.jpeg,.png"></label><?php endif;?><label>Details<textarea name="details" maxlength="5000" required></textarea></label><p><?= $kind==='leave'?($coreReady?'Published holidays and assigned weekly offs are excluded. Half-day leave counts as 0.5 day. Requests require approval.':'Leave is counted in calendar days, including weekends and holidays. Paid leave requires an entitlement and Super Admin approval.'):($kind==='regularisation'?'Submit one date per correction. HR reviews the request and applies an audited attendance correction.':'Your request will be reviewed by the Super Admin.') ?></p><button class="primary" <?= !$ready?'disabled':'' ?>>Submit request</button></form></section><?php endif ?><section class="panel"><h2><?= $admin?'Review requests':'My request history' ?></h2><?php
 $records=[];if($ready){$q=$pdo->prepare('SELECT r.*,u.name FROM hr_requests r JOIN users u ON u.id=r.user_id WHERE r.kind=?'.($admin?'':' AND r.user_id=?').' ORDER BY r.id DESC LIMIT 100');$q->execute($admin?[$kind]:[$kind,$user['id']]);$records=$q->fetchAll(PDO::FETCH_ASSOC);}
 if(!$records)echo '<p class="empty">No requests yet.</p>';foreach($records as $r): ?><article class="request-card"><div class="panel-title"><h2><?=h($r['subject'])?></h2><span class="badge"><?=h($r['status'])?></span></div><p><?=h($r['name'])?> · <?=h($r['category'])?><?php if($r['start_date']): ?> · <?=h($r['start_date'])?> to <?=h($r['end_date'])?><?php endif ?></p><p class="request-detail"><?=nl2br(h($r['details']))?></p><?php if($r['status']==='Pending'): ?><form method="post" class="inline-actions"><?php token(); ?><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><input type="hidden" name="action" value="<?= $admin?'review':'cancel' ?>"><?php if($admin): ?><button class="primary" name="status" value="<?= $kind==='helpdesk'?'Resolved':'Approved' ?>"><?= $kind==='helpdesk'?'Resolve':'Approve' ?></button><button class="wide-button" name="status" value="Rejected">Reject</button><?php else: ?><button class="wide-button">Cancel request</button><?php endif ?></form><?php endif ?></article><?php endforeach ?></section>
<?php elseif($page==='announcements'): if($admin): ?><section class="panel"><h2>Publish company notice</h2><form method="post" class="work-form"><?php token(); ?><input type="hidden" name="action" value="announcement"><label>Title<input name="title" maxlength="180" required></label><label>Message<textarea name="details" maxlength="5000" required></textarea></label><button class="primary" <?= !$ready?'disabled':'' ?>>Publish notice</button></form></section><?php endif ?><section class="panel"><h2>Company notices</h2><?php $records=$ready?$pdo->query('SELECT title,body,created_at FROM hr_announcements ORDER BY id DESC LIMIT 50')->fetchAll(PDO::FETCH_ASSOC):[];if(!$records)echo '<p class="empty">No notices published yet.</p>';foreach($records as $r): ?><article class="request-card"><h2><?=h($r['title'])?></h2><small><?=h($r['created_at'])?></small><p class="request-detail"><?=nl2br(h($r['body']))?></p></article><?php endforeach ?></section>
<?php elseif($page==='profile'): ?><section class="panel"><h2><?=h($user['name'])?></h2><p><?=h($user['email']??'Email not added')?></p><p>Username: <?=h($user['username']??'Not assigned')?></p><div class="quick-links"><a class="primary" href="?page=employment">My employment details</a><a class="wide-button" href="?page=documents">My documents</a><a class="wide-button" href="?page=security">Login & security</a></div></section>
<?php elseif($page==='offboarding' && $admin): ?><section class="panel"><h2>Employee access</h2><p>Deactivate an employee account when their access should end. Records and request history are retained. Their next protected request will be denied.</p><div class="table-scroll"><table><thead><tr><th>Employee</th><th>Email</th><th>Status</th><th>Action</th></tr></thead><tbody><?php foreach($pdo->query("SELECT id,name,email,active FROM users WHERE role='employee' ORDER BY name") as $r):?><tr><td><?=h($r['name'])?></td><td><?=h($r['email'])?></td><td><?=$r['active']?'Active':'Inactive'?></td><td><?php if($r['active']):?><form method="post" data-confirm="Deactivate this employee's login access?"><?php token();?><input type="hidden" name="action" value="deactivate"><input type="hidden" name="id" value="<?=(int)$r['id']?>"><button class="danger-button" <?=!$ready?'disabled':''?>>Deactivate account</button></form><?php endif?></td></tr><?php endforeach?></tbody></table></div></section><section class="panel"><h2>Exit workflows</h2><div class="quick-links"><a class="primary" href="?page=exit_tasks">Clearance checklist</a><a class="wide-button" href="?page=assets">Asset returns</a><a class="wide-button" href="?page=payroll">Final payroll</a></div></section>
<?php elseif(in_array($page,['system','security'],true)): ?><section class="panel"><?php if($passwordSetup):?><h2>Set your personal password to open your dashboard</h2><p>Your account requires a password change before you can use employee pages. This happens after a new account is created or an administrator resets your password.</p><p>Enter the password you just used to sign in, then choose a different password with 12–72 characters. After saving, your dashboard will open automatically.</p><?php else:?><h2>Change my password</h2><?php endif;?><form class="work-form" method="post"><?php token();?><input type="hidden" name="action" value="change_password"><label>Current password<input type="password" name="current_password" autocomplete="current-password" required></label><label>New password<input type="password" name="new_password" autocomplete="new-password" minlength="12" maxlength="72" required></label><label>Confirm new password<input type="password" name="confirm_password" autocomplete="new-password" minlength="12" maxlength="72" required></label><button class="primary" <?=!$ready?'disabled':''?>><?=$passwordSetup?'Save password and open dashboard':'Update password'?></button></form></section><?php if($admin):?><section class="panel"><h2>HR module database</h2><p><?= $suiteReady?'Additional HR tables are installed.':'Install the HR tables to enable the new modules. Existing data will be preserved.' ?></p><form method="post"><?php token();?><input type="hidden" name="action" value="suite_install"><button class="primary">Install / update HR modules</button></form></section><section class="panel"><h2>System status</h2><div class="module-items"><div>Database connection<span>Connected</span></div><div>Workspace tables<span><?=$ready?'Installed':'Migration required'?></span></div><div>Access roles<span>Super Admin / Employee</span></div><div>Session idle timeout<span>30 minutes</span></div><div>Biometric integration<span>Not connected</span></div></div></section><?php endif ?>
<?php elseif($page==='audit' && $admin): ?><section class="panel"><h2>Activity history</h2><div class="table-scroll"><table><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Record</th></tr></thead><tbody><?php if($ready)foreach($pdo->query('SELECT a.*,u.name FROM hr_audit a JOIN users u ON u.id=a.actor_id ORDER BY a.id DESC LIMIT 100') as $r): ?><tr><td><?=h($r['created_at'])?></td><td><?=h($r['name'])?></td><td><?=h($r['action'])?></td><td><?=h($r['record_id'])?></td></tr><?php endforeach ?></tbody></table></div></section>
<?php else:
 $modules=[
 'attendance'=>['Attendance','Attendance records', $admin?['Live punch dashboard','Present, absent and late arrivals','Monthly calendar & export']:['My punches','Monthly attendance calendar','Late login, early exit & overtime']],
 'devices'=>['Biometric integration','eSSL device management',['Device registration','Employee-ID mapping','Sync errors & retry queue','Device & API logs']],
 'shifts'=>['Attendance policy','Shift and time rules',['Shift schedules','Late login & early exit','Overtime','Night shifts']],
 'holidays'=>['Leave & holidays','Company calendar',['Holiday calendar','Team leave calendar','CL, SL, PL and LWP policies']],
 'payroll'=>['Payroll',$admin?'Monthly payroll':'My payslips',$admin?['Salary structures','Attendance & leave deductions','Overtime & incentives','Payroll approval','Payroll history & payslips']:['Payslip download','Salary breakdown','Payment history']],
 'recruitment'=>['Recruitment','Find your next teammate',['Job openings','Candidate tracker','Interview scheduling & status','Offer-letter checklist']],
 'onboarding'=>['Onboarding',$admin?'New joiner checklist':'My joining checklist',['Joining tasks','Document collection','Onboarding progress']],
 'performance'=>['Performance',$admin?'Goals and reviews':'My goals and reviews',['Goals & KPI tracking','Review cycles','Review history']],
 'reports'=>['Reports','Company reports',['Headcount by department','Attendance summary','Leave summary','Payroll summary','Downloadable reports']],
 'settings'=>['Company settings','Two-role access model',['Company profile','Departments & designations','Attendance policies','Leave policies','Payroll configuration']]
 ];$m=$modules[$page];empty_module($m[0],$m[1],$m[2]);
 endif; ?>