<?php
// Only role-checked entry points may load this file.
if (!isset($user)) { http_response_code(404); exit; }
$admin=$user['role']==='super_admin';
$nav=$admin?['overview'=>'Overview','employees'=>'Employees','attendance'=>'Attendance','devices'=>'Biometric devices','shifts'=>'Shifts & rules','regularisation'=>'Regularisation','leaves'=>'Leave management','holidays'=>'Holidays','payroll'=>'Payroll','recruitment'=>'Recruitment','onboarding'=>'Onboarding','performance'=>'Performance','announcements'=>'Announcements','helpdesk'=>'Helpdesk','reports'=>'Reports','audit'=>'Audit log','settings'=>'Company settings']:['overview'=>'My dashboard','profile'=>'My profile','attendance'=>'My attendance','regularisation'=>'Regularisation','leaves'=>'My leave','holidays'=>'Holiday calendar','payroll'=>'My payslips','onboarding'=>'My onboarding','performance'=>'My performance','announcements'=>'Company notices','helpdesk'=>'My requests'];
$page=$_GET['page'] ?? 'overview';
if (!isset($nav[$page])) { http_response_code(403); exit('This section is not available for your role.'); }
$pdo=db(); $notice=''; $error=''; $ready=true;
try { $pdo->query('SELECT id FROM hr_requests LIMIT 1'); $pdo->query('SELECT id FROM hr_announcements LIMIT 1'); $pdo->query('SELECT id FROM hr_audit LIMIT 1'); } catch(Throwable $e) { $ready=false; }
function audit_action(PDO $pdo,int $actor,string $action,int $record): void { $pdo->prepare('INSERT INTO hr_audit(actor_id,action,record_id) VALUES(?,?,?)')->execute([$actor,$action,$record]); }
function field_text(string $key,int $max,bool $required=true): string { $s=trim((string)($_POST[$key] ?? '')); if (($required && $s==='') || strlen($s)>$max) throw new InvalidArgumentException('Please complete all fields within their character limits.'); return $s; }
if ($_SERVER['REQUEST_METHOD']==='POST') {
 csrf();
 try {
  if (!$ready) throw new InvalidArgumentException('The workspace database migration must be installed first.');
  $action=$_POST['action'] ?? '';
  $pdo->beginTransaction();
  if ($action==='create_employee' && $admin && $page==='employees') {
   $name=field_text('name',150); $email=strtolower(field_text('email',190)); $password=(string)($_POST['password'] ?? '');
   if (!filter_var($email,FILTER_VALIDATE_EMAIL) || strlen($password)<12 || strlen($password)>72) throw new InvalidArgumentException('Use a valid email and a password of 12–72 characters.');
   $pdo->prepare("INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,'employee')")->execute([$name,$email,password_hash($password,PASSWORD_DEFAULT)]);
   audit_action($pdo,(int)$user['id'],'employee.created',(int)$pdo->lastInsertId());
  } elseif ($action==='announcement' && $admin && $page==='announcements') {
   $pdo->prepare('INSERT INTO hr_announcements(title,body,author_id) VALUES(?,?,?)')->execute([field_text('title',180),field_text('details',5000),$user['id']]);
   audit_action($pdo,(int)$user['id'],'announcement.published',(int)$pdo->lastInsertId());
  } elseif ($action==='request' && !$admin && in_array($page,['leaves','regularisation','helpdesk'],true)) {
   $kind=['leaves'=>'leave','regularisation'=>'regularisation','helpdesk'=>'helpdesk'][$page];
   $category=field_text('category',40); $subject=field_text('subject',180); $details=field_text('details',5000); $start=null; $end=null;
   $allowed=$kind==='leave'?['CL','SL','PL','LWP']:($kind==='regularisation'?['Missed punch','Incorrect punch','Shift correction']:['HR','Payroll','IT','Other']);
   if (!in_array($category,$allowed,true)) throw new InvalidArgumentException('Choose a valid category.');
   if ($kind!=='helpdesk') {
    $start=field_text('start_date',10); $end=field_text('end_date',10);
    foreach([$start,$end] as $date) { $d=DateTimeImmutable::createFromFormat('!Y-m-d',$date); if (!$d || $d->format('Y-m-d')!==$date) throw new InvalidArgumentException('Choose valid dates.'); }
    if ($end<$start) throw new InvalidArgumentException('End date cannot be before start date.');
   }
   $pdo->prepare('INSERT INTO hr_requests(user_id,kind,category,subject,details,start_date,end_date) VALUES(?,?,?,?,?,?,?)')->execute([$user['id'],$kind,$category,$subject,$details,$start,$end]);
   audit_action($pdo,(int)$user['id'],$kind.'.submitted',(int)$pdo->lastInsertId());
  } elseif (in_array($action,['review','cancel'],true) && in_array($page,['leaves','regularisation','helpdesk'],true)) {
   $kind=['leaves'=>'leave','regularisation'=>'regularisation','helpdesk'=>'helpdesk'][$page];
   $id=filter_var($_POST['id'] ?? '',FILTER_VALIDATE_INT); if (!$id || $id<1) throw new InvalidArgumentException('Invalid request.');
   $q=$pdo->prepare('SELECT * FROM hr_requests WHERE id=? AND kind=? FOR UPDATE');$q->execute([$id,$kind]);$r=$q->fetch(PDO::FETCH_ASSOC);
   if (!$r || $r['status']!=='Pending') throw new InvalidArgumentException('This request is no longer pending.');
   if ($action==='review' && $admin) {
    $status=$_POST['status'] ?? ''; $allowed=$kind==='helpdesk'?['Resolved','Rejected']:['Approved','Rejected'];
    if (!in_array($status,$allowed,true)) throw new InvalidArgumentException('Invalid status.');
   } elseif ($action==='cancel' && !$admin && (int)$r['user_id']===(int)$user['id']) { $status='Cancelled'; }
   else { throw new InvalidArgumentException('You cannot change this request.'); }
   $pdo->prepare('UPDATE hr_requests SET status=?,reviewer_id=? WHERE id=?')->execute([$status,$user['id'],$id]); audit_action($pdo,(int)$user['id'],$kind.'.'.strtolower($status),$id);
  } else { throw new InvalidArgumentException('This action is not available for your role.'); }
  $pdo->commit(); header('Location: '.($admin?'super-admin.php':'employee.php').'?page='.urlencode($page).'&saved=1'); exit;
 } catch(InvalidArgumentException $e) { if($pdo->inTransaction())$pdo->rollBack(); $error=$e->getMessage(); }
 catch(Throwable $e) { if($pdo->inTransaction())$pdo->rollBack(); $error='Unable to save. Check that the email is unique and the database is configured.'; }
}
function token(): void { echo '<input type="hidden" name="csrf" value="'.h($_SESSION['csrf']).'">'; }
function empty_module(string $title,string $description,array $items): void { echo '<section class="panel"><span class="eyebrow">'.h($title).'</span><h2 style="margin:12px 0">'.h($description).'</h2><p>Not configured yet. No live records are available in this module.</p><div class="module-items">';foreach($items as $item)echo '<div>'.h($item).'<span>Not connected</span></div>';echo '</div></section>'; }
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h($nav[$page])?> · PeopleFlow</title><link rel="icon" href="assets/favicon.svg"><link rel="stylesheet" href="assets/style.css"><link rel="stylesheet" href="assets/workspace.css"></head><body><aside><a class="brand" href="index.php"><i>p.</i> peopleflow<span>ARKENTECH</span></a><div class="workspace"><span class="company-icon">A</span><div><b><?= $admin?'Super Admin':'Employee' ?></b><small>Arkentech Solutions</small></div></div><p class="nav-label"><?= $admin?'COMPANY WORKSPACE':'MY WORKSPACE' ?></p><nav><?php foreach($nav as $key=>$label): ?><a class="<?= $key===$page?'active':'' ?>" href="?page=<?=h($key)?>"><?=h($label)?></a><?php endforeach ?></nav><div class="aside-bottom"><button id="theme" type="button">◐ Switch appearance</button><form action="logout.php" method="post"><?php token(); ?><button class="wide-button">Sign out ↪</button></form></div></aside><div class="main"><header><button id="menu" class="mobile-menu" aria-label="Toggle navigation" aria-expanded="false">☰</button><span><?= $admin?'Company workspace':'Employee workspace' ?> / <?=h($nav[$page])?></span><span><?=h($user['name'])?></span></header><main id="content"><div class="page-title"><div><span class="eyebrow"><?= $admin?'YOUR PEOPLE, IN ONE PLACE':'YOUR WORKDAY, SIMPLIFIED' ?></span><h1><?=h($nav[$page])?></h1><p><?= $admin?'Manage your team and review employee requests.':'Your personal records, updates and requests.' ?></p></div><span class="badge"><?= $admin?'Super Admin':'Employee' ?></span></div><?php if(!$ready): ?><div class="error" role="alert">Workspace setup is incomplete. Ask your administrator to import database/002-workspaces.sql.</div><?php endif ?><?php if($error): ?><div class="error" role="alert"><?=h($error)?></div><?php endif ?><?php if(isset($_GET['saved'])): ?><div class="success" role="status">Saved successfully.</div><?php endif ?>
<?php if($page==='overview'):
 $total=$admin?(int)$pdo->query("SELECT COUNT(*) FROM users WHERE role='employee' AND active=1")->fetchColumn():null;
 $pending=0; $approved=0;
 if($ready){$q=$pdo->prepare('SELECT status,COUNT(*) n FROM hr_requests'.($admin?'':' WHERE user_id=?').' GROUP BY status');$q->execute($admin?[]:[$user['id']]);foreach($q as $r){if($r['status']==='Pending')$pending=$r['n'];if($r['status']==='Approved')$approved=$r['n'];}}
 ?><div class="stats"><section class="stat lavender"><div><?= $admin?'Active employees':'My requests' ?></div><strong><?= $admin?$total:($ready?$pending:'—') ?></strong><small><?= $admin?'Employee accounts':'Pending review' ?></small></section><section class="stat mint"><div><?= $admin?'Pending requests':'Approved requests' ?></div><strong><?= $ready?($admin?$pending:$approved):'—' ?></strong><small>Leave, attendance and helpdesk</small></section><section class="stat peach"><div>Attendance today</div><strong>—</strong><small>Biometric connection pending</small></section><section class="stat blue"><div><?= $admin?'Payroll':'My payslip' ?></div><strong>—</strong><small>Payroll setup pending</small></section></div><section class="panel"><h2>Hello, <?=h($user['name'])?>.</h2><p style="margin:12px 0">Choose a section to <?= $admin?'manage employee accounts, review requests or publish company notices.':'submit leave, request an attendance correction or contact your team.' ?></p><div class="quick-links"><a class="primary" href="?page=leaves"><?= $admin?'Review leave':'Apply for leave' ?> →</a><a class="wide-button" href="?page=announcements">Company notices →</a><a class="wide-button" href="?page=helpdesk">Helpdesk →</a></div></section>
<?php elseif($page==='employees' && $admin): ?><section class="panel"><h2>Create employee account</h2><form method="post" class="work-form"><?php token(); ?><input type="hidden" name="action" value="create_employee"><label>Full name<input name="name" maxlength="150" required></label><label>Work email<input name="email" type="email" maxlength="190" required></label><label>Initial password<input name="password" type="password" minlength="12" maxlength="72" autocomplete="new-password" required></label><p>New accounts receive Employee access only. Share the initial password privately.</p><button class="primary" <?= !$ready?'disabled':'' ?>>Create employee</button></form></section><section class="panel"><h2>Employee directory</h2><div class="table-scroll"><table><thead><tr><th>Name</th><th>Email</th><th>Account status</th></tr></thead><tbody><?php foreach($pdo->query("SELECT name,email,active FROM users WHERE role='employee' ORDER BY name") as $r): ?><tr><td><?=h($r['name'])?></td><td><?=h($r['email'])?></td><td><?= $r['active']?'Active':'Inactive' ?></td></tr><?php endforeach ?></tbody></table></div></section>
<?php elseif(in_array($page,['leaves','regularisation','helpdesk'],true)):
 $kind=['leaves'=>'leave','regularisation'=>'regularisation','helpdesk'=>'helpdesk'][$page];
 if(!$admin): ?><section class="panel"><h2><?= $page==='leaves'?'Apply for leave':($page==='regularisation'?'Request attendance correction':'Submit a request') ?></h2><form class="work-form" method="post"><?php token(); ?><input type="hidden" name="action" value="request"><label>Category<select name="category"><?php foreach(($kind==='leave'?['CL','SL','PL','LWP']:($kind==='regularisation'?['Missed punch','Incorrect punch','Shift correction']:['HR','Payroll','IT','Other'])) as $c): ?><option><?=h($c)?></option><?php endforeach ?></select></label><label>Subject<input name="subject" maxlength="180" required></label><?php if($kind!=='helpdesk'): ?><div class="form-columns"><label>From<input type="date" name="start_date" required></label><label>To<input type="date" name="end_date" required></label></div><?php endif ?><label>Details<textarea name="details" maxlength="5000" required></textarea></label><p><?= $kind==='leave'?'Leave balances and holiday deductions are not configured yet. Requests require Super Admin review.':($kind==='regularisation'?'Approval records the decision; biometric punch corrections are not connected yet.':'Your request will be reviewed by the Super Admin.') ?></p><button class="primary" <?= !$ready?'disabled':'' ?>>Submit request</button></form></section><?php endif ?><section class="panel"><h2><?= $admin?'Review requests':'My request history' ?></h2><?php
 $records=[];if($ready){$q=$pdo->prepare('SELECT r.*,u.name FROM hr_requests r JOIN users u ON u.id=r.user_id WHERE r.kind=?'.($admin?'':' AND r.user_id=?').' ORDER BY r.id DESC LIMIT 100');$q->execute($admin?[$kind]:[$kind,$user['id']]);$records=$q->fetchAll(PDO::FETCH_ASSOC);}
 if(!$records)echo '<p class="empty">No requests yet.</p>';foreach($records as $r): ?><article class="request-card"><div class="panel-title"><h2><?=h($r['subject'])?></h2><span class="badge"><?=h($r['status'])?></span></div><p><?=h($r['name'])?> · <?=h($r['category'])?><?php if($r['start_date']): ?> · <?=h($r['start_date'])?> to <?=h($r['end_date'])?><?php endif ?></p><p class="request-detail"><?=nl2br(h($r['details']))?></p><?php if($r['status']==='Pending'): ?><form method="post" class="inline-actions"><?php token(); ?><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><input type="hidden" name="action" value="<?= $admin?'review':'cancel' ?>"><?php if($admin): ?><button class="primary" name="status" value="<?= $kind==='helpdesk'?'Resolved':'Approved' ?>"><?= $kind==='helpdesk'?'Resolve':'Approve' ?></button><button class="wide-button" name="status" value="Rejected">Reject</button><?php else: ?><button class="wide-button">Cancel request</button><?php endif ?></form><?php endif ?></article><?php endforeach ?></section>
<?php elseif($page==='announcements'): if($admin): ?><section class="panel"><h2>Publish company notice</h2><form method="post" class="work-form"><?php token(); ?><input type="hidden" name="action" value="announcement"><label>Title<input name="title" maxlength="180" required></label><label>Message<textarea name="details" maxlength="5000" required></textarea></label><button class="primary" <?= !$ready?'disabled':'' ?>>Publish notice</button></form></section><?php endif ?><section class="panel"><h2>Company notices</h2><?php $records=$ready?$pdo->query('SELECT title,body,created_at FROM hr_announcements ORDER BY id DESC LIMIT 50')->fetchAll(PDO::FETCH_ASSOC):[];if(!$records)echo '<p class="empty">No notices published yet.</p>';foreach($records as $r): ?><article class="request-card"><h2><?=h($r['title'])?></h2><small><?=h($r['created_at'])?></small><p class="request-detail"><?=nl2br(h($r['body']))?></p></article><?php endforeach ?></section>
<?php elseif($page==='profile'): ?><section class="panel"><h2><?=h($user['name'])?></h2><p><?=h($user['email'])?></p><p>Employee account #<?= (int)$user['id'] ?></p></section><?php empty_module('Employment details','Your employment record',['Department & designation','Reporting manager','Joining date','Documents & expiry reminders','Bank details','Emergency contact']); ?>
<?php elseif($page==='audit' && $admin): ?><section class="panel"><h2>Activity history</h2><div class="table-scroll"><table><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Record</th></tr></thead><tbody><?php if($ready)foreach($pdo->query('SELECT a.*,u.name FROM hr_audit a JOIN users u ON u.id=a.actor_id ORDER BY a.id DESC LIMIT 100') as $r): ?><tr><td><?=h($r['created_at'])?></td><td><?=h($r['name'])?></td><td><?=h($r['action'])?></td><td><?=h($r['record_id'])?></td></tr><?php endforeach ?></tbody></table></div></section>
<?php else:
 $modules=[
 'attendance'=>['Attendance','Attendance records', $admin?['Live punch dashboard','Present, absent and late arrivals','Monthly calendar & export']:['My punches','Monthly attendance calendar','Late login, early exit & overtime']],
 'devices'=>['Biometric integration','eSSL device management',['Device registration','Employee-ID mapping','Sync errors & retry queue','Device & API logs']],
 'shifts'=>['Attendance policy','Shift and time rules',['Shift schedules','Late login & early exit','Overtime','Night shifts']],
 'holidays'=>['Leave & holidays','Company calendar',['Holiday calendar','Team leave calendar','CL, SL, PL and LWP policies']],
 'payroll'=>['Payroll',$admin?'Monthly payroll':'My payslips',$admin?['Salary structures','Attendance & leave deductions','Overtime & incentives','Payroll approval','Payroll history & payslips']:['Payslip download','Salary breakdown','Payment history']],
 'recruitment'=>['Recruitment','Find your next teammate',['Job openings','Candidate tracker','Interview scheduling & status','Offer-letter checklist']],
 'onboarding'=>['Onboarding',$admin?'New joiner checklist':'My joining checklist',['Joining tasks','Document collection','Onboarding progress']],
 'performance'=>['Performance',$admin?'Goals and reviews':'My goals and reviews',['Goals & KPI tracking','Review cycles','Review history']],
 'reports'=>['Reports','Company reports',['Headcount by department','Attendance summary','Leave summary','Payroll summary','Downloadable reports']],
 'settings'=>['Company settings','Two-role access model',['Company profile','Departments & designations','Attendance policies','Leave policies','Payroll configuration']]
 ];$m=$modules[$page];empty_module($m[0],$m[1],$m[2]);
 endif; ?></main><footer>PeopleFlow by Arkentech<span><?= $admin?'Company workspace':'Employee workspace' ?></span></footer></div><script src="assets/workspace.js"></script></body></html>
