<dialog class="attendance-dialog" id="employee-csv-dialog" <?=isset($_SESSION['employee_csv_preview'])||($error&&in_array($_POST['action']??'',['preview_employee_csv','commit_employee_csv'],true))?'data-auto-open':''?>>
<h2>Bulk Add Employees</h2><p class="hint">Download the template, fill one employee per row, then upload to review. Up to 100 employees per file.</p>
<?php if($error):?><div class="alert error"><?=h($error)?></div><?php endif;?>
<a class="button" href="assets/employee-template.csv" download>Download CSV template</a>
<p>Required: first name, last name, department, designation and joining date (YYYY-MM-DD). Department and designation must match Company Settings. Other columns are optional. Blank usernames are generated automatically.</p>
<p class="hint">New accounts use the Employee role, Active status and Full Time employment. Initial password: User@123; a password change is required at first sign-in. Existing employee IDs, emails or usernames are skipped.</p>
<form method="post" enctype="multipart/form-data" class="form-grid"><?php ftoken();?><input type="hidden" name="action" value="preview_employee_csv"><label class="full">Employee CSV<input type="file" name="employee_csv" accept=".csv,text/csv" required><small>CSV UTF-8 · Maximum 2 MB</small></label><div class="form-actions full"><button class="button primary">Preview employees</button><button class="button" type="button" data-close-dialog>Close</button></div></form>
<?php if(!empty($_SESSION['employee_csv_preview'])):$preview=$_SESSION['employee_csv_preview'];?><h3>Review <?=count($preview)?> employees</h3><div class="table-scroll"><table class="directory"><thead><tr><th>Name</th><th>Employee ID</th><th>Department / designation</th><th>Joining date</th><th>Result</th></tr></thead><tbody><?php foreach($preview as $r):?><tr><td><?=h($r['first_name'].' '.$r['last_name'])?></td><td><?=h($r['employee_code']?:'Not assigned')?></td><td><?=h($r['department'])?><small><?=h($r['designation'])?></small></td><td><?=h($r['joining_date'])?></td><td><?=!empty($r['_skip'])?'Skip duplicate':'Add employee'?></td></tr><?php endforeach;?></tbody></table></div><form method="post" class="form-actions" data-confirm="Add the new employees shown in this preview? Existing accounts remain unchanged."><?php ftoken();?><input type="hidden" name="action" value="commit_employee_csv"><button class="button primary">Add employees</button></form><?php endif;?>
</dialog>
