<?php
function fi(string $name):string {$icons=['overview'=>'▦','employees'=>'♙','settings'=>'⚙','departments'=>'▤','designations'=>'◇','roles'=>'◎','account'=>'◉'];return $icons[$name]??'↗';}
function fnav(string $key,string $label):void {global $page;echo '<a href="?page='.h($key).'" '.($page===$key||($key==='employees'&&str_starts_with($page,'employee-'))?'class="selected" aria-current="page"':'').'><span aria-hidden="true">'.fi($key).'</span>'.h($label).'</a>';}
function field(string $key,string $label,array $v,string $type='text',bool $required=false,int $max=190):void {echo '<label>'.h($label).($required?' <span aria-label="required">*</span>':'').'<input type="'.h($type).'" name="'.h($key).'" value="'.h($v[$key]??'').'" maxlength="'.$max.'" '.($required?'required':'').'></label>';}
function choose(string $key,string $label,array $v,array $options):void {echo '<label>'.h($label).'<select name="'.h($key).'">';foreach($options as $o)echo '<option '.(($v[$key]??'')===$o?'selected':'').'>'.h($o).'</option>';echo '</select></label>';}
function fbadge(string $text,bool $ok=true):void {echo '<span class="badge '.($ok?'':'muted-badge').'">'.h($text).'</span>';}
$hasLogo=$installed?(bool)$pdo->query("SELECT id FROM hr_media WHERE purpose='company_logo' LIMIT 1")->fetchColumn():false;
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h($pages[$page][0])?> · PeopleFlow</title><link rel="stylesheet" href="assets/foundation.css"><script src="assets/foundation.js" defer></script></head><body>
<aside class="sidebar" id="navigation"><a class="brand" href="index.php"><b>p.</b><span>peopleflow<small>ARKENTECH HRMS</small></span></a><div class="company-switch"><?php if($hasLogo):?><img src="media.php" alt="Company logo"><?php else:?><span class="company-icon">▥</span><?php endif;?><span><?=h($company['name'])?><small>People & culture</small></span></div><p class="nav-caption">WORKSPACE</p><nav aria-label="Main navigation"><?php foreach(['overview','employees'] as $key)if(can($pdo,$user,$pages[$key][1]))fnav($key,$key==='overview'?'Overview':'People');?><p class="nav-caption">ADMINISTRATION</p><?php foreach(['settings','departments','designations','roles'] as $key)if(can($pdo,$user,$pages[$key][1]))fnav($key,$pages[$key][0]);?></nav><div class="sidebar-bottom"><?php fnav('account','My account');?><form method="post" action="logout.php"><?php ftoken();?><button class="logout-button">↪ <span>Sign out</span></button></form></div></aside>
<div class="app"><header class="topbar"><button class="icon-button menu-toggle" aria-label="Toggle navigation" aria-expanded="false" aria-controls="navigation">☰</button><span class="breadcrumb"><?=h($company['name'])?> <span>›</span> <strong><?=h($pages[$page][0])?></strong></span><div class="top-actions"><button class="icon-button" id="theme-toggle" aria-label="Toggle dark mode">◐</button><a class="user-link" href="?page=account"><span class="avatar small"><?=h(strtoupper(substr($user['name'],0,1)))?></span><span><?=h($user['name'])?><small><?=$user['role']==='super_admin'?'Super Administrator':'Team workspace'?></small></span></a></div></header>
<main id="main"><div class="page-heading"><div><p class="eyebrow"><?=in_array($page,['settings','departments','designations'],true)?'COMPANY SETTINGS':'PEOPLEFLOW WORKSPACE'?></p><h1><?=h($page==='overview'?'Good '.((int)date('H')<12?'morning':'afternoon').', '.explode(' ',$user['name'])[0]:$pages[$page][0])?></h1><p class="subtitle"><?=h(['overview'=>"Here’s what’s happening with your people today.",'employees'=>'Your complete employee directory, in one place.','settings'=>'The company details used across your workspace.','departments'=>'Organize your teams and their department heads.','designations'=>'Manage job titles and their department assignments.','roles'=>'Create roles and choose exactly what each role can access.'][$page]??'Manage your people with care.')?></p></div><?php if($installed&&$page==='employees'&&can($pdo,$user,'employees.create')):?><a class="button primary" href="?page=employee-add">+ Add employee</a><?php endif;?></div>
<?php if($notice):?><div class="alert success" role="status"><?=h($notice)?></div><?php endif;?><?php if($error):?><div class="alert error" role="alert"><?=h($error)?></div><?php endif;?>
<?php if(!$installed):?><section class="card empty-state"><h2>Set up the Phase 1 foundation</h2><p>This adds company settings, employee profiles and configurable roles, preserving your existing users and records.</p><form method="post"><?php ftoken();?><input type="hidden" name="action" value="install_foundation"><button class="button primary">Install Phase 1 database</button></form></section><?php else:
if(in_array($page,['settings','departments','designations'],true)):?><nav class="tabs" aria-label="Company settings"><?php foreach(['settings'=>'Company profile','departments'=>'Departments','designations'=>'Designations'] as $k=>$label)if(can($pdo,$user,$pages[$k][1])):?><a href="?page=<?=$k?>" <?=$page===$k?'aria-current="page"':''?>><?=$label?></a><?php endforeach;?></nav><?php endif;
if($page==='overview')require __DIR__.'/overview.php';elseif(str_starts_with($page,'employee'))require __DIR__.'/people.php';elseif(in_array($page,['settings','departments','designations','roles'],true))require __DIR__.'/settings.php';else require __DIR__.'/account.php';endif;?>
<footer class="page-footer">PeopleFlow · <?=h($company['name'])?></footer></main></div></body></html>
