<?php
$counts=$pdo->query("SELECT COUNT(*) total,COALESCE(SUM(u.active=1),0) active,COALESCE(SUM(e.department_id IS NULL OR e.designation_id IS NULL OR e.joining_date IS NULL OR u.email IS NULL),0) incomplete FROM employees e JOIN users u ON u.id=e.user_id WHERE e.deleted_at IS NULL")->fetch(PDO::FETCH_ASSOC);
$departmentCount=(int)$pdo->query('SELECT COUNT(*) FROM departments WHERE active=1')->fetchColumn();$designationCount=(int)$pdo->query('SELECT COUNT(*) FROM designations WHERE active=1')->fetchColumn();$total=(int)$counts['total'];$active=(int)$counts['active'];$percent=$total?round($active/$total*100,1):0;
$months=[];$growth=[];for($i=5;$i>=0;$i--){$start=new DateTimeImmutable('first day of this month');$m=$start->modify("-$i months");$months[]=$m->format('M');$q=$pdo->prepare('SELECT COUNT(*) FROM employees WHERE deleted_at IS NULL AND joining_date IS NOT NULL AND joining_date<=?');$q->execute([$m->format('Y-m-t')]);$growth[]=(int)$q->fetchColumn();}
$max=max(1,...$growth);$points=[];foreach($growth as $i=>$n)$points[]=($i*100).','.round(150-$n/$max*125,1);$line=implode(' ',$points);
$month=(string)($_GET['month']??date('Y-m'));if(!preg_match('/^\d{4}-(0[1-9]|1[0-2])$/',$month))$month=date('Y-m');$monthDate=new DateTimeImmutable($month.'-01');$monthNumber=(int)$monthDate->format('n');
$q=$pdo->prepare('SELECT u.id,u.name,e.birth_date,e.joining_date FROM employees e JOIN users u ON u.id=e.user_id WHERE e.deleted_at IS NULL AND u.active=1 AND (MONTH(e.birth_date)=? OR MONTH(e.joining_date)=?) ORDER BY u.name');$q->execute([$monthNumber,$monthNumber]);$events=[];foreach($q->fetchAll(PDO::FETCH_ASSOC) as $r){foreach(['birth_date'=>'Birthday','joining_date'=>'Work anniversary'] as $col=>$kind){if($r[$col]&&(int)date('n',strtotime($r[$col]))===$monthNumber&&substr($r[$col],0,4)<=$monthDate->format('Y')){$events[]=['id'=>$r['id'],'name'=>$r['name'],'day'=>(int)date('j',strtotime($r[$col])),'kind'=>$kind];}}}usort($events,fn($a,$b)=>$a['day']<=>$b['day']);$eventDays=array_column($events,'day');
$pending=[];if($user['role']==='super_admin')$pending=$pdo->query("SELECT r.*,u.name FROM hr_requests r JOIN users u ON u.id=r.user_id WHERE r.status='Pending' ORDER BY r.created_at LIMIT 5")->fetchAll(PDO::FETCH_ASSOC);
?>
<div class="stats"><?php foreach([['♙','Total people',$total,'Employees in your directory'],['◷','Active accounts',$active,'Accounts enabled for sign-in'],['▦','Departments',$departmentCount,'Active departments'],['◇','Designations',$designationCount,'Active job titles']] as [$icon,$label,$number,$note]):?><section class="card stat"><span class="stat-icon" aria-hidden="true"><?=$icon?></span><span class="stat-label"><?=$label?></span><strong class="stat-value"><?=$number?></strong><small><?=$note?></small></section><?php endforeach;?></div>
<div class="dashboard-grid"><section class="card"><div class="card-heading"><div><p class="eyebrow">YOUR PEOPLE</p><h2>Employee account status</h2></div><?php if(can($pdo,$user,'employees.view')):?><a class="link" href="?page=employees">View people ↗</a><?php endif;?></div><div class="donut-row"><div class="donut" style="--percent:<?=$percent?>%" role="img" aria-label="<?=$percent?> percent active accounts"><span><?=$percent?>%<small>Active</small></span></div><div class="legend"><p><span><i></i>Active</span><strong><?=$active?></strong></p><p><span><i></i>Inactive</span><strong><?=$total-$active?></strong></p><p><span>Total employees</span><strong><?=$total?></strong></p></div></div><div class="insight">Account availability is shown here. Attendance is managed separately.</div></section>
<section class="card"><div class="card-heading"><div><p class="eyebrow">WORKFORCE</p><h2>People growth</h2></div><span class="badge muted-badge">Last 6 months</span></div><strong class="stat-value"><?=end($growth)?></strong><span class="hint">Current employees with a joining date</span><svg class="chart" viewBox="0 0 500 165" role="img" aria-label="Cumulative employee joining counts: <?=h(implode(', ',array_map(fn($m,$n)=>$m.' '.$n,$months,$growth)))?>"><path d="M0 150 H500 M0 90 H500 M0 25 H500" stroke="var(--line)" stroke-dasharray="3 4" fill="none"/><polygon points="0,160 <?=$line?> 500,160" fill="var(--light)"/><polyline points="<?=$line?>" fill="none" stroke="#85b315" stroke-width="2.5"/><?php foreach($points as $pt):[$x,$y]=explode(',',$pt);?><circle cx="<?=$x?>" cy="<?=$y?>" r="3" fill="#85b315"/><?php endforeach;?></svg><div class="chart-labels"><?php foreach($months as $m):?><span><?=$m?></span><?php endforeach;?></div><p class="hint">Profiles without a joining date are excluded.</p></section>
<section class="card"><div class="card-heading"><div><p class="eyebrow"><?=h(strtoupper($monthDate->format('F Y')))?></p><h2>Company calendar</h2></div><div class="actions"><a class="button small" aria-label="Previous month" href="?page=overview&month=<?=$monthDate->modify('-1 month')->format('Y-m')?>">‹</a><a class="button small" aria-label="Next month" href="?page=overview&month=<?=$monthDate->modify('+1 month')->format('Y-m')?>">›</a></div></div><table class="calendar"><thead><tr><?php foreach(['MON','TUE','WED','THU','FRI','SAT','SUN'] as $d):?><th scope="col"><?=$d?></th><?php endforeach;?></tr></thead><tbody><?php $offset=(int)$monthDate->format('N')-1;$days=(int)$monthDate->format('t');for($cell=0;$cell<ceil(($offset+$days)/7)*7;$cell++):if($cell%7===0)echo '<tr>';$day=$cell-$offset+1;$valid=$day>0&&$day<=$days;$today=$valid&&$month.'-'.str_pad((string)$day,2,'0',STR_PAD_LEFT)===date('Y-m-d');?><td class="<?=$today?'today ':''?><?=$valid&&in_array($day,$eventDays,true)?'event':''?>"><span><?=$valid?$day:''?></span></td><?php if($cell%7===6)echo '</tr>';endfor;?></tbody></table><p class="hint">Purple dots mark birthdays and joining anniversaries.</p></section>
<section class="card"><div class="card-heading"><div><p class="eyebrow">INBOX</p><h2>Pending approvals</h2></div></div><?php if($pending):foreach($pending as $r):?><div class="list-row"><span class="avatar small"><?=h(substr($r['name'],0,1))?></span><div class="grow"><strong><?=h($r['name'])?></strong><small><?=h(ucfirst($r['kind']).' · '.$r['subject'])?></small></div><a class="button small" href="?page=<?=h(['leave'=>'leaves','regularisation'=>'regularisation','helpdesk'=>'helpdesk'][$r['kind']])?>">Review ↗</a></div><?php endforeach;else:?><div class="empty-state"><span class="empty-icon" aria-hidden="true">✓</span><h3><?=$user['role']==='super_admin'?'You’re all caught up':'Approvals are managed by Super Admin'?></h3><p><?=$user['role']==='super_admin'?'No requests are waiting for review.':'Your role permissions control the sections you can access.'?></p></div><?php endif;?></section>
<section class="card"><div class="card-heading"><div><p class="eyebrow">PEOPLE · <?=h(strtoupper($monthDate->format('F')))?></p><h2>Celebrations</h2></div></div><?php if(!$events):?><p class="hint">No birthdays or joining anniversaries recorded for this month.</p><?php else:foreach($events as $event):?><div class="list-row"><span class="avatar small"><?=h(substr($event['name'],0,1))?></span><div class="grow"><strong><?=h($event['name'])?></strong><small><?=h($event['kind'])?></small></div><span class="badge muted-badge"><?=$event['day'].' '.$monthDate->format('M')?></span></div><?php endforeach;endif;?></section>
<section class="card"><div class="card-heading"><div><p class="eyebrow">WORKSPACE HEALTH</p><h2>Keep your directory up to date</h2></div></div><p class="hint"><?=$counts['incomplete']?> profiles need a department, designation, joining date or work email. Employee IDs can be added whenever you’re ready.</p><?php if(can($pdo,$user,'employees.view')):?><p><a class="button" href="?page=employees&incomplete=1">Review incomplete profiles ↗</a></p><?php endif;?></section></div>
